#+startup: content indent

* Disco Elysium - Day 1

I heard an strange voice, telling me about emptiness, trying to keep
me from going back to the word. I enjoyed the silence, until the only
option left was to "Take me there". That went too far, sudently I was
scared of death. I didn't want to die, so I demanded do be brought
back in the world. The voice warned me that the word was not a place
I will enjoy, but I procedded anyway. The other option seemed worse.

Then, I suddently woke up naked and really tired. All my clothes
were scattered across the room, a cold breeze was coming from the
window, which was smashed by something. I couldn't remember anything,
not even how I looked like or where I was. I started exploring the room
and picking up my clothes from the ground, my nekctie was hunging from
the fan, a music tape was broken. I figured out that I was missing one
of my shoes so I probably throw the other one outside the window,
breaking it; so I headed outside to get my other shoe.

According to a random blonde girl in her 20' just outside my door, I
am a (drunk) policemen, sent to the city to investigate a dead body in
the back of the motel. I did not remember anything, the girl claims that
I made a lot of noise the night prior. Indded, her desciption matches
the conditions of the room: a broken window from a shoe, music tape
destroyed, an empty bottle of alcohol and clothes everywhere.
According to the girl, I came in the city three days prior, during
the night I screamed "I don't want to be this kind of anymal".
I still can't remember anything about It.

The current season was winter. We were in the year 51 of "this century",
It was monday. I leared a bit about the city and that there has been a
failed revolution here. Apparently the economy embraced the free
market and and empty life full of dancing... what a real shit.

I didn't want to bother the blonde girl anymore, so I headed downstairs
where there were a hall and a bar. The door to the kitchen was reserved
to the staff until 13:00, It was 8:45 so I thought I could check this
place later. The mess hall was reserved to Union members and It opens
at 16:00. There was a sleeping man in the hall, an old lady, a cafeteria
manager, one of my collegues and a karaoke place. I had to resist the
temptation to sing something in the karaoke, what did I have to sing
about anyway?

I met my buddy Kim Kitsuragi from precinct 57. I am from 41,
apparently. For some reason I didn't have my badge with me, I needed to
report this as soon as possible. Even If I didn't remember anything, I
pretended to be a police officer, hoping that memories would come back
soon.

I wen to to talk to the cafetteria manager, his name is Garte. He did not
call the police, he claimed; It was probably Sylvie, another bartender
that works there, he usggested. He have us her number. Garte tells us
that people say that it was the Union dockworkers who hand the body in
the tree, It was an execution. But who is the murdered person, and why
did this group wanted to kill him? Garte talls us that the man was a
security guard for the harbour company, a merchenary, and the Union
probably wanted to send a message.

Ah shit, I had to pay the damages I did the days prior, and the
accomodation, but I really had no money. This was quite a bad situation,
I needed to find 120 coins or I would have no other place to rest except
the streets. Fuck, I couldn't even remember where I lived, I was
thinking hard about it.

I went outside and used Kim's radio to talk to the station and report
that I am missing my badge, I also realised I couldn't find my gun
anymore. The police station laughed at me and denied me any money, I
was really fucked. They called me Dick Mullen but I don't know
If that is my real name, maybe I should have asked for money before
reporting the missing badge...

I then called Sylvie with the number that Garte gave us. She told us
that she did not make the call, and that not many people had phones
those days. The Union had a phone and there was one further down the
coast. Additionally, she seemed afraid to talk with me, she explained
that a few days before I was playing with my gun and making very
explicit suicide jokes. I had to move with this case quickly.

There wasn't much of interest in the immediate surroundings of the
motel, just a few workers and a kid, so I deaded to the corpse's
location. There was some a really inpolite kid talking in third
person who thought he was the main protagonist of the world. My morale
is really low right now, I don't know why I am here or why am am doing
everything that I am doing. Hell, I don't even know anything about
myself...

I started getting closer to the dead body and inspecting It's
surroundings. I found footprints for eight paires of work boots just
under the body. Some of them stood out: some light steps, maybe from
a woman or a kid, a sole smoother than the other, maybe a taxi driver
or someone working with a pedal, and two heavy footprints, probably
two people one on top of the other to carry the body, but why did
they need to carry the body? Was It already dead? The footprints
appeared to be a week old.

I could not get other useful information, and I didn't have the
strength to move the body, do I started exploring the city. I went
to a book shop and bought a very cheap tourist map of the city, It is
quite old but It does the job. I entered a shop where I sold some
cans that I found for some coins.

There is a huge crowd east of the hotel, I went to check on them.
Apparently the gates to the factory are blocked by a big racist guy
and the workers are asking and protesting to open the door and let
them do their work, but he does not move an inch. I knew I could
never beat him, so I tried to convince him that we shared the same
ideas, hoping that we would treat me in a more friendly way, so
we started talking about races. Sadly, we wants me to internalize
what we have discussed and come back later. So I wen away
internalizing it, with real disconfort. I want to stay away as much
as possible from politics, this is a dangerous thing.

I head north to an apartment building and talk with some people
over there: a negotiator for the strike who told us more about
what was happening, and a potential witness who does not want to
talk. We entered and explored It's building but he does not want
to open the door. We arrainged to check again the day after at 21:00.

We then go south, and discover some trails of a car running away
from the crime scene and making crazy manouvers, this is very
suspicious. Everytihng happened whiting the last 72 hour, the car
looks like It is either a Coupris 40 or a Linnea G22.

Wednesday 7:15 souther canal.

** Meetings

- Wednesday 7:15 souther canal.
- Tomorrow at 21:00 the smoking guy in the balcony.
- Tomorrow evening in the motel behind the curtains.

* Notes
** Who am I?

The only notable information is that I am a policeman, and probably
not a really good one since I can't even remember who I am. But the
policement instincts are still here, as if they were subconcious.
I have a white rectangle on my uniform, the same as a colligue of mine.
It is probably the logo of my police department.

** The city

The city is Revachol district of Martenaise, the former capital of
the world now managed by foreigners. There has been a failed
=revolution= and now the ciry thinks that the only solution is free
market and disco music.  The city is located in the Insulindian Isula,
the symbol of Its discovery is a great sjua (basically an eagle).

** What happened to the city?

There was a big strike, the head was Mr. Claire. Joice Messier was
sent as a negotiator.

** What about this revolution?

-----

Travel: [[file:disco-elysium.org][Disco elysium]], [[file:../../theindex.org][Index]]
