#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../subjects.org][Subjects]] >

* Mathematics
#+INDEX: Giovanni's Diary!Mathematics

One of the things I am more grateful for to university is getting me
introduced to the ideas of Mathematics. During high school, I had math
as one of the primary subjects, we went through the basics of algebra
and calculus up until integrals. In university the pace changed, and I
noticed I was not used to *thinking* about math.

Up until my last year of bachelor, math was all about a lot of
exercises, memorizing formulas and "pattern match" problems. This was
how I was taught for my entire life and it took me a great effort and
time to leave this mentality.

At my last year I finally began developing a kind of maturity for math
and only then I really started enjoying it. It surely requires a lot
of thinking and intellectual effort but I find it rewarding, here I
will document my journey in the realm of mathematics.

-- [[file:notes.org][notes]] - [[../feeds/feedMath.rss][RSS feed]] -

-----

Travel: [[file:../subjects.org][Subjects]], [[file:../theindex.org][Index]]
