#+startup: content indent

[[file:index.org][Giovanni's Diary]] >

* About Me
#+INDEX: Giovanni's Diary!About Me

Hi, I am Giovanni.
I was born in the city of Senigallia in the east coast of Italy. Later
my family was joined by two younger brothers and one sister.

** Early life

I don't have many memories of my early childhood. When I was about 10
(I think) I began playing minecraft 1.5.2 and watching youtube videos
about the game. The oldest videos I recall are the ones of
"EternalLove" and another guy playing on xbox which I cannot remember
the name. My first world was in creative mode, I was in an island and
I was slowly learning what blocks were available and how they worked
in the game. I later started a survival world which I would continue
for many years, my base was in a swamp biome.

After a family trip in norther Italy I remember I was curious about
"how do people make computer programs", so I asked my dad, which is not
an expert, but he hinted that they were made with programming languages
"like C++". When I came back home I started looking what was this "c++".
I downloaded dev-c++ and began writing classic programs like text
based games with decision trees. I still have many of those.

#+begin_src cpp
  #include<cstdlib>
  #include<iostream>
  #include<fstream>

  //Programma aventura

  using namespace std;

  int main(int argc, char *argv[])
  {//Inizio
    int scelta;

    system("cls");
    cout<<"Matteo deve fare la spesa in brevissimo tempo e non sa se arrivera'in orario."<<endl;
    cout<<"Davanti a lui ci sono due strade: una piu'lunga, ma piu'sicura e l'altra piu'corta in cui Matteo non ci era mai passato"<<endl;
    cout<<"Matteo deve prendere:"<<endl;
    cout<<"1.La strada sicura"<<endl;
    cout<<"2.La strada piu'corta"<<endl;

    cout<<"Scelta: ";//1 2
    cin>>scelta;
    cout<<endl;

    switch(scelta);
    {
      {//Inizio caso 1
        case 1:

          int scelta2;

          cout<<"Matteo passa per la strada sicura, ma dei lavori bloccano la strada."<<endl;
          cout<<"Matteo deve:"<<endl;
          cout<<"3.Tornare indietro e fare la strada piu'corta"<<endl;
          cout<<"4.Cercare di superare i lavori"<<endl;

          cout<<"Scelta: ";//3 4
          cin>>scelta2;
          cout<<endl;

          switch(scelta2);

          ...
#+end_src

When I was about 13 I began watching youtube videos on how to make
videogames with Unity engine and I made my own little horror games. I
remember spending most of my wake time watching these videos,
programmingin C# and playing either minecraft of The Sims 1.

During the same time I wanted to make youtube videos myself so I
started a [[https://www.youtube.com/@San7oS][gaming channel]] where I would play minecraft and other
games. This was a crazy yourney: I learned so many thing like advanced
redstone, video editing and recording, creating miniatures with
photoshop and so many other things. I was really invested in my
minecraft world and I remember this period as an happy one because I
had always so many redstone projects in mind and I was working on
something that made me proud. However, even good things come to an end
and by 2019 my perfectionism was making me anxious and depressed
because everything had to be perfect and I could not allow myself any
errors. I decided to quit the channel out of frustration and play
other games like Dark Souls 1 and Skyrim.

** High School

I attended the Liceo Scientifico "Enrico Medi" where I participated in
programming Olympiads and cybersecurity competitions. I was doing good
in the competitions, reaching nationals every time and this made me
choose the path ahead: I wanted to be a computer scientist.  In
particular, I participated in the cyberchallenge which is an
university CTF competition and I arrived first place and competed in
the nationals. During this time, I met probably the greatest
programmer I know, Leonardo Taccari, which is part of the board of
NetBSD and a true UNIX fellow. I asked him suggestions about books to
learn UNIX and he suggested me "Advanced Programming in the Unix
Environment", a book that I bought and read all the way in the
following months. Later this book would influence me to dig deeper in
operating systems and UNIX kernels and stay close to the operating
systems world.

Yet, I was a very shy and introverted person, and I lacked any type of
social skills. I was very isolated and I would never leave my room
other than for going to school just to feel even more isolated. This
was really hard mentally, I needed to do something to help my mental
sanity. On my last year of high school I began pushing myself out of
my comfort zone and participating in some activities like theater
courses. This was the bravest decision of my life and It would change
the course of it. Slowly, I started getting used to going outside of
my room and being surrounded by other people, something I was greatly
struggling (and still do sometimes). I also met F which helped me a
lot with my self confidence and isolation.

The last year of high school was different from the others. I found
some people to talk to, I did creative writing, public speaking and
theater. I also travelled by myself for the fist time: I went to
Sicily several times, I still remember those days vividly, then to
Florence for a performance and to Turin for the national final of the
cybersecurity olimpiads. I graduated with top marks and I started
writing my diary.

** University

I continued my studies in Computer Science in Trento, in the Italian
Alps.

The first year I was feeling a lot of pressure and anxiety, yet I
managed to be stoic about It and kept pushing through. At the end of
January 2023 I travelled across Europe with interrail alone, this was
meant as a voyage of self discovery and I wrote hundreds of pages of my
diary. It was a period where I felt stuck and I was uncertain about my
future. In the second half of the year I began volunteering in the
local hiking association. I was organizing hikes for groups of kids, I
felt a lot of responsibility but I also had a lot of fun. I learned a
lot. In the summer I went one week in the mountains and I joined a
folk dances group.

In my second year at university was a difficult year, by the end of it
I went through a big breakdown that would follow me for another
year. I decided to focus fully on studying computer science, which is
what I have always liked. I began intermediate projects like a [[https://github.com/San7o/Brenta-Engine][game
engine]] and a [[https://github.com/San7o/Baldo-Scanner][vulnerability scanner]] and I got into Linux kernel
development and cloud computing.

To be continued...

-----

Travel: [[file:index.html][Giovanni's Diary]], [[file:theindex.org][Index]]
