#+startup: content indent

[[file:index.org][Giovanni's Diary]] > [[file:first-page.org][First Page]] >

* Documenting my Life
#+INDEX: Giovanni's Diary!Documenting my Life

I have always been fascinated by the idea of documenting my life. I
get to save some moments and thoughts to reflect upon later, It
helps me to have a better sense of myself and my direction. In some
way It is a proof of my existence, a side effect of my being.

The way I have been documenting my time is always changing, this diary
is just the latest of my iterations. Yet, It creates something I will
look back to with a sense of nostalgia. After all, history has started
when we humans began to document it, most of what came before is now
lost and I think it is a shame.

I wish I had more data about what I did when I was little, or about my
first days of high school, or during my lowest moments. This keeps me
motivated to document what I am going through now, even when It seems
to be unimportant.

-----

Travel: [[file:first-page.org][First Page]]
