#+startup: content indent

[[file:index.org][Giovanni's Diary]] >

* Subjects
#+INDEX: Giovanni's Diary!Subjects

You are in the subject page. This file serves as an hub to reach other
areas of interest of mine where I have written some notes. If you
prefer, you can also explore the diary [[file:autobiography/chronological.org][chronologically]].

I enjoy talking about [[file:programming/programming.org][programming]], in particular [[file:programming/linux/linux.org][linux]], and [[file:math/mathematics.org][math]]. I
[[file:writing/writing.org][write]] various things, such as notes on my [[file:reading/reading.org][readings]] or [[file:writing/poetry/poetry.org][poetry]]. Anything
else that I do goes in my [[file:stash/stash.org][stash]]. At the end of each page you will find
the [[file:theindex.org][index]] page which is useful to move around if you lost your way.

Additionally, I have various [[file:wishlist.org][wishlists]] of future projects and [[file:feeds.org][RSS
Feeds]].

Feel free to [[file:contacts.org][contact me]] any time.

-----

Travel: [[file:first-page.org][First Page]], [[file:theindex.org][Index]]
