#+startup: content indent

[[file:index.org][Giovanni's Diary]] >

* Wish list :global:
#+INDEX: Giovanni's Diary!Wishlist

This document contains my wishlist for future projects that do not
belong to any of the other wishlists. Generally, each section of
this wiki has It's own wishlist which you can access from the
home pages.

I use *org-agenda* to manage all the *TODO* items in the different
wishlist files. Just for completeness, here is a list of the other
wishlist files:

- [[file:reading/wishlist.org][reading wishlist]]
- [[file:programming/wishlist.org][programming wishlist]]
- [[file:programming/emacs/wishlist.org][emacs wishlist]]

** TODO Add more style

This website is quite minimal and I really like this, yet I think I
can work more on the presentation and the style of navigation. I want
to experiment with some ASCII art in the future.

** TODO Improve the About Me page

Add a sort of autobiografy to the page. From there, you could expand
It with additional information about my past in other pages. This
would make me reflect about my past and document It so that I won't
forget.

-----

Travel: [[file:index.org][Giovanni's Diary]], [[file:theindex.org][Index]]
