#+startup: content indent

[[file:index.org][Giovanni's Diary]] > [[file:subjects.org][Subjects]] >

* Wish list :global:
#+INDEX: Giovanni's Diary!Wishlist

This document contains my wishlist for future projects that do not
belong to any of the other wishlists. Generally, each section of
this wiki has It's own wishlist which you can access from the
home pages.

I use *org-agenda* to manage all the *TODO* items in the different
wishlist files. Just for completeness, here is a list of the other
wishlist files:

- [[file:reading/wishlist.org][reading wishlist]]
- [[file:programming/wishlist.org][programming wishlist]]
- [[file:programming/emacs/wishlist.org][emacs wishlist]]


** TODO Check out the indie web carnival

https://indieweb.org/IndieWeb_Carnival

** TODO Add a normie blog page

Add a normal-looking blog page to navigate the website in a more
familiar way.

** TODO Add more style

This website is quite minimal and I really like this, yet I think I
can work more on the presentation and the style of navigation. I want
to experiment with some ASCII art in the future.

-----

Travel: [[file:subjects.org][Subjects]], [[file:theindex.org][Index]]
