#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../subjects.org][Subjects]] > [[file:reading.org][Reading]] >

* Blogs
#+INDEX: Giovanni's Diary!Reading!Blogs

It is really hard do find *good* blogs, especially the ones I like. Here
is a curated list of my favorite blogs:

- *[[https://protesilaos.com/feeds/][Protesilaos Stavrou]]*: Prot is a well known member of the emacs
  community, he is also a very unique person. He lives alone in a poor
  area in the mountains, with just a few hours of electricity if there
  is sun, and maintains various emacs packages. He has an education in
  philosophy and a youtube channel where he mainly talks about emacs,
  philosophy and him building his modest house. There is really a lot
  to learn from a person like him.
- *[[https://sachachua.com/blog/feed/index.html][Sacha chua]]*: Very frequent writer and another famous face in the
  emacs community. I read her posts basically everyday, lots of
  interesting stuff especially if you are interested in emacs and
  random trivias about packages.
- *[[https://blogsystem5.substack.com/feed][Julio Merino]]*: I found him on hackernews and It really fitted my
  interests. The guy talks about low level programming / hardware and
  he is very knowledgeable about it, one of the true OGs. I find all
  of his blogs really interesting and with an old school feel.
- *[[https://www.antirez.com/rss][Salvatore Sanfilippo]]*: Finally some Italian here! Salvatore is an
  exceptional programmer and the founder of [[https://github.com/redis/redis][Redis]]. He is always very
  interesting to listen to, he has a youtube channel and often has
  strong opinions about software and work life, which I admire.
- *[[https://lwn.net/][LWN]]* : The main medium for talking about the linux kernel other
  than the mailing lists, LWN is a very important website in the
  history and development of the linux community.
- *[[https://eli.thegreenplace.net/feeds/all.atom.xml][Eli Bendersky]]*: Very interesting, he often delves into math which I
  really enjoy.
- *[[https://www.phoronix.com/rss.php][Phoronix]]*: The best news site for linux kernel related things,
  after LWN. I noticed that whenever I was looking for benchmarks, the
  best were always from a certain Michael Larabel, so I dig deeper and
  discovered his website and his [[https://github.com/phoronix-test-suite/phoronix-test-suite][software]] to do benchmarking, which is
  totally awesome.
- *[[https://www.brendangregg.com/blog/rss.xml][Brendan Gregg]]*: Very competent programmer focusing on performance
  evaluation. He created the [[https://github.com/brendangregg/FlameGraph][flamegraph]] tool.
- *[[https://blog.vaxry.net/feed][Vaxry]]*: This is the blog of the creator of [[https://github.com/hyprwm/Hyprland][Hyprland]]. Even if I
  don't use hyprland anymore, he is a true gigachad and most of the
  development of Hyprland was carried by him alone.
- *[[https://arxiv.org/][Arxiv]]*: This isn't really a blog, but Its a scientific publications
  website. I am subscribed to some subjects and I regularly read
  It. It's my main source of catching up with the state of the art.
  
And many many more, those are only a few honorable mentions. I will
try to keep this list up to date.
	
To *discover blogs*, what I usually do is:
- browse [[https://news.ycombinator.com/][hackernews]] daily
- stalker people in mailing lists / open source projects that I follow
- look at [[https://indieblog.page/all][indieblog]] sometimes
- in general, be curious about the people behind the code, and assume
  that every decent programmer has a blog
I use [[https://www.gnus.org/][gnus]] as my *feeds aggregator*.

-----

Travel: [[file:reading.org][Reading]], [[file:../theindex.org][Index]]
