#+startup: content indent

* Blogs

It is really hard do find *good* blogs, especially the ones I like,
which are mostly hidden treasures in a sea of AI garbage content. Here
is a curated list of my favourite blogs:

- *Protesilaos Stavrou* https://protesilaos.com/feeds/: Prot is a well
	known member of the emacs community, he is also a very unique
	person. He lives alone in a poor area in the mountains, with just
	a few hours of electricity if there is sun. He has an education in
	philosophy and a youtube channel where he mainly talks about emacs,
	phylosophy and him building his modest house. There is really a lot
	to learn from a person like him.
- *Sacha chua* https://sachachua.com/blog/feed/: Very frequent writer
	and another famous face in the emacs community. I read her posts
	basically everyday, lots of interesting stuff especially if you are
	interested in emacs and random trivias about packages.
- *Irreal* https://irreal.org/blog/: I am going quick with the famous
	ones, Irreal is another very frequent blogger about emacs and nerdy
	technology. Many posts are very interesting, mostly cool trings
	worth sharing.
- *Julio Merino* https://blogsystem5.substack.com/feed: I found him on
	hackernews and It really fitted my interests. The guy talks about
	low level programming / hardware and he is very knowledgable about
	it, one of the true OGs. I find all of his blogs really interesring
	and with an old school feel.
- *Salvatore Sanfilippo* https://www.antirez.com/rss: Finally some
	italian here! Salvatore is an exceptional programmer and the founder
	of Redis. He is always very interesting to listen to, he has a youtube
	channel and often has strong opinions about software and work life,
	which I admire.
- *Seed of Science* https://www.theseedsofscience.pub/feed: A non tech
	blog, this is a real tresure. The topics very from nature to art,
	science and ideas. All the posts are really fascinating and often
	worth reading.
- *LWN* https://lwn.net/: The main medium for talking about the linux
	kernel other than the mailing lists, LWN is a very important website
	in the history and developement of the linux community.
- *Eli Bendersky* https://eli.thegreenplace.net/feeds/all.atom.xml:
	Very interesting, tech experiences.
- *Vaxry* https://blog.vaxry.net/feed: This is the blog of the creator
	of Hyprland. Even if I don't use hyprland anymore, he is a true
	gigachad and most of the development of Hyprland was carried by him
	alone.
- *Arxiv* https://arxiv.org/: This isn't really a blog, but Its a
  scientific publications website. I am subscibed to some subjects
  and I regularly read It. It's my main source of catching up with
  the state of the art.
  
And many many more, those are only a few honorable mentions. I will
try to keep this list up to date.
	
To *discover blogs*, what I usually do is:
- browse [[https://news.ycombinator.com/][hackernews]] daily
- stalker people in mailing lists / open source projects that I follow
- look at [[https://indieblog.page/all][indieblog]] sometimes
- in general, be curous about the people behind the code, and assume
  that every decent programmer has a blog
I use [[https://www.gnus.org/][gnus]] as my *feeds aggregator*.

---

Go Back: [[file:reading.org][reading]]
