#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../subjects.org][Subjects]] > [[file:reading.org][Reading]] >

* Blogs
#+INDEX: Giovanni's Diary!Reading!Blogs

Here is a curated list of my favorite blogs:

- *[[https://protesilaos.com/feeds/][Protesilaos Stavrou]]*: Prot is a well known member of the emacs
  community, he is also a very unique person. He lives alone in a poor
  area in the mountains, with just a few hours of electricity if there
  is sun, and maintains various emacs packages. He has an education in
  philosophy and a youtube channel where he mainly talks about emacs,
  philosophy and him building his modest house. There is really a lot
  to learn from a person like him.
- *[[https://blogsystem5.substack.com/feed][Julio Merino]]*: I found him on hackernews and it really fitted my
  interests. He talks about low level programming / hardware and he is
  very knowledgeable about it. I find all of his blogs really
  interesting and with an old school feel.
- *[[https://www.antirez.com/rss][Salvatore Sanfilippo]]*: Finally some Italian here! Salvatore is an
  exceptional programmer and the founder of [[https://github.com/redis/redis][Redis]]. He is always very
  interesting to listen to, he has a youtube channel and often has
  strong opinions about software and work life, which I admire.
- *[[https://lwn.net/][LWN]]* : The main medium for talking about the linux kernel other
  than the mailing lists, LWN is a very important website in the
  history and development of the linux community.
- *[[https://people.kernel.org/read/feed/][people.kernel.org]]*: a collection of blog posts from kernel
  maintainers.
- *[[https://eli.thegreenplace.net/feeds/all.atom.xml][Eli Bendersky]]*: Very interesting, he often delves into math which I
  really enjoy.
- *[[https://www.phoronix.com/rss.php][Phoronix]]*: The best news site for linux kernel related things,
  after LWN. I noticed that whenever I was looking for benchmarks, the
  best were always from a certain Michael Larabel, so I dig deeper and
  discovered his website and his [[https://github.com/phoronix-test-suite/phoronix-test-suite][software]] to do benchmarking, which is
  totally awesome.
- *[[https://www.brendangregg.com/blog/rss.xml][Brendan Gregg]]*: Very competent programmer focusing on performance
  evaluation. He created the [[https://github.com/brendangregg/FlameGraph][flamegraph]] tool.
- *[[https://news.ycombinator.com/][HackerNews]]*: I browse HackerNews daily to see what people are
  talking about.
- *[[https://lobste.rs/][lobste.rs]]*: Similar to HackerNews, but more technical
- *[[https://blog.vaxry.net/feed][Vaxry]]*: This is the blog of the creator of [[https://github.com/hyprwm/Hyprland][Hyprland]]. Even if I
  don't use hyprland anymore, he is a 10x programmer.
- *[[https://arxiv.org/][Arxiv]]*: This isn't really a blog, but its a scientific publications
  website. I am subscribed to some subjects and I regularly read it (I
  mainly follow cs.OS, and some others for fun). It's my main source
  for discovering papers.
- Other programmers: *[[https://www.bellard.org/][Fabrice Bellard]]*, *[[https://fabiensanglard.net/rss.xml][Fabien Sanglard]]*, *[[https://kevingal.com/feed.xml][kevingal]]*,
  *[[https://www.daemonology.net/blog/index.rss][Colin Percival]]*, *[[http://www.aaronsw.com/2002/feeds/pgessays.rss][Paul Graham]]*
- AI: *[[https://huyenchip.com/feed.xml][Chip Huyen]]*
- Great Mathematicians / Scientists I follow: *[[https://www.jeremykun.com/index.xml][Math ∩ Programming]]*,
  *[[https://terrytao.wordpress.com/feed/][Terence Tao]]*, *[[https://writings.stephenwolfram.com/feed/][Stephen Wolfram]]*, *[[https://johncarlosbaez.wordpress.com/feed/][Azimuth]]*.
- I also follow many more people on Mastodon and on Youtube
  
And many many more, those are only a few mentions. I will try to keep
this list up to date.
	
To discover blogs, I usually:
- browse [[https://news.ycombinator.com/][hackernews]] daily
- stalker people in mailing lists / open source projects that I follow
- look at [[https://indieblog.page/all][indieblog]] sometimes
- in general, be curious about the people behind the code, and assume
  that most good programmers have a blog

I use [[https://www.gnus.org/][gnus]] as my feeds aggregator.

-----

Travel: [[file:reading.org][Reading]], [[file:../theindex.org][Index]]
