#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../subjects.org][Subjects]] > [[file:reading.org][Reading]] >

* My Favourite Readings
#+INDEX: Giovanni's Diary!Reading!My Favourite Readings

In this note I will try to collect the most influential and Favourite
readings I have done over my lifetime. This is in continuous evolution
as I discover (or remember) things.

In no particular order:

- [[https://learnopengl.com/][learnopengl.com]]: this is how I started with 3D graphics, which
  eventually became [[https://github.com/San7o/Brenta-Engine][Brenta-Engine]]. It may not be the best guide out
  there, but I would totally recommend it to anybody that wants to
  start working with 3D graphics.
- [[https://github.com/nothings/stb][stb]]: collection of header only libraries. This inspired me to write
  my own [[https://github.com/San7o/micro-headers][micro-headers]] and to enter this "sub-genre" of header only,
  easy to reuse libraries.
- [[https://www.learncpp.com/][learncpp.com]]: the absolute best resource to learn about c++, other
  than the great [[https://en.cppreference.com/index.html][cppreference]]. This made me appreciate the language
  greatly and motivated me to program more and more. C++ conferences
  on youtube are great too.
- the [[https://www.linuxfromscratch.org/lfs/][linuxfromscratch]] book: compiling and maintaining my own Linux system
  from scratch has been one of the best educational projects I have
  ever done. I became much more competent and, I have to say, fearless
  when it comes to compiling programs / dependencies and customizing
  the Linux kernel.
- [[https://en.wikipedia.org/wiki/Hackers:_Heroes_of_the_Computer_Revolution][Hackers: Heroes of the Computer Revolution]]: great historical book
  about hacker culture and the beginning of computing. A wonderful and
  informative read, it made me familiar with the legendary names that
  shaped the computer world.
- [[https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html][Intel® 64 and IA-32 Architectures Software Developer’s Manual]]: the
  reference for the Intel architecture. I have nothing else to say,
  this is such a monumental book that tells you how to use the
  CPU. Super important for writing an operating system on Intel.
  
-----

Travel: [[file:reading.org][Reading]], [[file:../theindex.org][Index]]
