#+startup: content indent

* Reading

I do like reading, actually most of my wake time is spent either
reading or writing on emacs. I would say that most of what I read
is either documentation, code, scientific papers and blog posts.
In fact, Iam a huge fan of blogs and they are my main source of
brain-bread.

TODO: I will put somewhere here a list of the blogs I follow, hopefully
one that auto-updates itself. It is really hard do find good blogs,
expecially the ones I like, which are mostly hidden gems in a sea
of AI garbage content.

To discover blogs, what I usually do is:
- browse https://news.ycombinator.com/ daily
- stalker people in mailing lists / open source projects that I follow
- look at https://indieblog.page/all sometimes
- in general, be curous about the people behind the code, and assume
  that every decent programmer has a blog
I use https://www.gnus.org/ as my feeds aggregator.
  
I also read books sometimes, I like history so there is almost
some element of history in anything that I read. Here you will
find some notes related to my readings:

- file:mauro-corona/mauro-corona.org

** Wishlist

I maintain a wishlist of future reading or writings here:
file:wishlist.org

Go back: file:../index.html
