#+startup: content indent

[[file:../index.org][Giovanni's Diary]] >

* Reading
#+INDEX: Giovanni's Diary!Reading

I am always reading something. Most of what I read now is either
documentation, code, scientific papers and [[file:blogs.org][blog posts]].  In fact, I am
a huge fan of blogs and they are my main source of brain-bread.

I was not an avid reader when I was young, I'd say I spent more time
playing [[file:../videogames/videogames.org][videogames]].  During my last year of high school I took a
creative writing class, I did some public speaking, did theater and
I started writing a diary journal.

After moving in the Italian Alps, I began hiking which became a great
passion of mine. I wanted to get closer to this culture so I started
reading [[file:mauro-corona/mauro-corona.org][Mauro Corona]]. To re-explore creative writing, I started a
series called [[file:surroundings/surroundings.org][surroundings]] where I talk about places. Sometime I feel
creative, sometime I want to learn about history, some other times I
like to be a guide. I learned about [[file:stoicism/stoicism.org][Stoicism]] as a way of facing life.

-- [[file:wishlist.org][wishlist]] --

-----

Travel: [[file:../index.html][Giovanni's Diary]], [[file:../theindex.org][Index]] 
