#+startup: content indent

* Wish list :reading:

This document contains my wishlist for future readings or writings.


** TODO Reading
My next books in the shelf:

- Mauro Corona, Lunario Sentimentale. 192 pag.
- Mauro Corona, Storie del bosco Antico, 160 pag.
- Mauro Corona, Voci del Bosco, 144 pag.
- Hermann Hesse, Narciso e Boccadoro

I want to re-explore Agatha Cristie. I read some of her books and
I was glued to the story, in particular "10 Piccoli Indiani".

** Writing

*** TODO Write short descriptions of my sourrounding

I had this idea to go to various places and just describe what
I see. Other that being a good exercise on writing, I think that
when I will be older I would want to read some descriptions on
how places looked like, more precisely, how did I feel them.
I think this is an invaluable thing to have and a good way to
break from coding.

*** TODO Write about Hermann Hesse

I have ready some books of Herman Hesse and I found them
interesting, so I want to talk about them. In particular:
- Siddharta
- Il lupo della Steppa

Go Back: file:reading.org
