#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../../subjects.org][Subjects]] > [[file:../reading.org][Reading]] > [[file:mauro-corona.org][Mauro Corona]] > [[file:notes.org][Notes]] >

* Vayont: Quelli del dopo
#+INDEX: Giovanni's Diary!Reading!Mauro Corona!Vajot: Quelli del dopo

This short book records a dialogue between the old inhabitants of the
village of Erto, which got almost completely destroyed by the
[[https://en.wikipedia.org/wiki/Vajont_Dam][disaster of the Vajont Dam]]. There have been various depictions of this
terrible event, the most famous probably being the 2001 film "Vajont -
La diga del disonore" by Renzo Martinelli which displayed the tragedy
to a modern audience via the cinema, raising awareness to the general
population. While the film focuses on the people in charge of
constructing and engineering the dam itself, in this book Mauro Corona
writes what the people of the disappeared houses think about all of this
in the context of a conversation at a bar, being one of them himself.

All the protagonists of this dialogue have been deeply effected by the
event, except maybe from the bartender whom was born only
after. Therefore, some people react emotionally, others are more
cynic, everybody has a deep hate to the government and the people in
management before and after the event. The 2001 film does not show
it, but the inhabitants of Erto are not really polite and
sophisticated: they have pride and they swear a lot.

All of this was captured in this raw dialogue. Soon, all the people
that witnessed the tragedy will live this world, making this book an
historic source.

-----

Travel: [[file:./mauro-corona.org][Mauro Corona]], [[file:../../theindex.org][Index]]
