#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] >

* Mauro Corona
#+INDEX: Giovanni's Diary!Reading!Mauro Corona

Mauro Corona is an Italian wood carver who lived much of his life
within **mountains** and rural mountain villages. Unsurprisingly, he
writes about that as well.

He has a deep love for mountain life, which fascinates me very
much. His books reflect his raw experience in this world, nothing
more than this but It is everything.

I am reading many of his books, some of my thoughts are accessible
in the following documents:

- [[file:mauro-corona-la-casa-dei-sette-ponti.org][La casa dei sette ponti]]
- [[file:mauro-corona-lunario-sentimentale.org][Lunario Sentimentale]]
- [[file:mauro-corona-le-voci-del-bosco.org][Le voci del bosco]]
- [[file:mauro-corona-la-via-del-sole.org][La via del sole]]
- [[file:mauro-corona-vayont-quelli-del-dopo.org][Vajont: Quelli del dopo]]
  
-----

Travel: [[file:../reading.org][Reading]], [[file:../../theindex.org][Index]]
