#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] > [[file:mauro-corona.org][Mauro Corona]] >

* Lunario Sentimentale
#+INDEX: Giovanni's Diary!Reading!Mauro Corona!Lunario Sentimentale

#+begin_src
  In questo calendario sentimentale, descrivo un'epopea perduta,
  ormai scomparsa per sempre.
#+end_src
"In this sentimental calendar, I describe a lost epic, now gone forever"

As the second book in my collection of Mauro Corona, I went with
Lunario Sentimentale. This was exactly the book I was looking for
when I was asking the internet for a book about rural mountain life,
which led me to discover Mauro Corona and his other books.

Lunario Sentimentale is a collection of memories of the author,
divided in seasons and months to emphasize how much the changing
of the season would shape the life of the people. Each month was
dedicated to something: preparing tools, fertilize the earth,
remembering the dead, etc. Life was hard in every moment of the year,
without mercy. Still, people were hard to put down and life kept
going.

As the author states several times, this book is a testimony of a
lost time. He describes his memories of cutting down trees with hand
saws before the electric saw were invented, of creating their own
tools each year, of hunting animals for surviving, of big snowfalls.
The author is clearly nostalgic about his time, his testimony will
make It last a bit longer before being totally surpassed by time
itself.

He speaks of a lost time in three different meaning: the first being
the lost mountain life and traditions which have been replaced by
electric tools and a fast paced economy. Second is the setting: the
author lived in the Vajont valley, an area that has been totally
destroyed by the fall of the dam that caused more than 2000 deaths, a
great tragedy in Italian history. Some of the places he describes do
not exist anymore as they were destroyed by the strength of the water.
Lastly, he speaks about friends and families that have long gone and
live only in his memories and words.

Nature is as an important actor as the protagonist himself. The work
was based around the changing of the seasons, on the time to grow and
harvest food, etc. Mauro talks about nature with great respect and
knowledge. In another book, "Storie del bosco antico", he talks about
his deep affections for the trees and their unique personalities.

Supernatural beliefs were also a part of normal life. People were
scared of witches, people would disappear without a reason sometimes,
there was a culture of myth. For example, the author thought (and
still does probably) that cutting a Christmas tree during a full
moonlight would make the tree last for years, instead of just a few
months.

Celebrations and christian culture were important: February was the
month of the masks, November was the month of the dead, December was
the month of Christmas.

This book is a window to a time that is probably lost forever and can
only be told by the few remaining people who lived it. Life was hard
but simple. People were happier, the author argues.

-----

Travel: [[file:./mauro-corona.org][Mauro Corona]], [[file:../../theindex.org][Index]]
