#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../../subjects.org][Subjects]] > [[file:../reading.org][Reading]] > [[file:mauro-corona.org][Mauro Corona]] > [[file:notes.org][Notes]] >

* Le voci del bosco
#+INDEX: Giovanni's Diary!Reading!Mauro Corona!Le voci del bosco

My third reading of Mauro Corona is "Le voci del bosco" which when
translated means "The voices of the forests". In the book, the author
describes how he sees and feels trees, whom he has a personal
relationship with. Other than a writer, the author is a wood carver
and he is greatly devoted to nature. His descriptions are subjective,
assigning a distinct personality to each kind of tree as if they were as
part of nature as us humans. Those feelings and memories were
developed after an entire lifetime surrounded by trees, which are
really special to the author.

Do not expect to get anything useful from the book. The author jumps
from tree to tree following his memories and feelings, like a stream
of consciousness. The olive tree is an old man carved by time and
accepting his death by letting be cut easily, he is kind and generous
by being easy to burn. Beeches are great and esteemed workers, they
wish to rebel from their destiny but then the humans come and make
tools out of them so they close in on themselves. The Spruce is a
noble, and so on...

There is a great variety of trees in nature, all of them so different
from the other. Each tree is good or bad for certain things like tools
or decoration or for fire, some trees prefer to grow in some places
rather than others, some trees are easy to cut or have a certain color
that sticks out. Those and more are what makes each tree have their
own personality, vices and virtues.

At the end, I learned to appreciate nature more in its variety. Now I
know a things or two about trees and I will be more mindful when I
meet one.

-----

Travel: [[file:./mauro-corona.org][Mauro Corona]], [[file:../../theindex.org][Index]]
