#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] >

* Surroundings
#+INDEX: Giovanni's Diary!Reading!Surroundings

*Surroundings* is a series of descriptions of places I find myself
into.  It is a raw translation of what my eyes see looking outward,
filtered by my own mind, in the historical period I live in. The
purpose of these writings is to provide a testimony of what a place
looks like and feels like in a certain moment. It indirectly records
what I, Giovanni, notice and pay attention to and feel, in this
particular moment of my life.

This series started as a creative writing experiment but naturally
introduced various historical elements. I do not claim to be an
historian. I gained all my knowledge unconventionally, by hiking to
places and listening to others during the years. These documents
became my attempts to write down this knowledge to the best of my
abilities and memory.

Read the chapters [[file:chapters.org][here]], or use the [[file:map.org][map]]. You can get the pdf book [[file:Surroundings.pdf][here]].

Subscribe to the RSS [[file:../../feeds/feedSurroundings.rss][feed]] to stay up to date with new releases.

-----

Travel: [[file:../reading.org][Reading]], [[file:../../theindex.org][Index]]
