#+startup: content indent

* Surroundings

*Surroundings* is a series of descriptions of places I find myself into.
It is a raw translation of what my eyes see looking outward, filtered
by my own mind, in the historical period I live in. The purpose of
those writings is to provide a testimony of what a place looks like
and feels like in a certain moment. It indirectly records what I,
Giovanni, notice and pay attention to and feel, in this particular
moment of my life.

Subscribe to the RSS [[file:../../feeds/feedSurroundings.rss][feed]] to stay up to date with new releases.

#+INDEX: Giovanni's Diary!Reading!Surroundings

*** Chapters

- [[file:san-marco-garden.org][San Marco garden]]
- [[file:sant-agata-church.org][Sant'Agata Church]]
- [[file:doss-trento.org][Doss Trento]]
- [[file:mount-san-martino.org][Mount San Martino]]
- [[file:sant-apollinare-church.org][Sant'Apollinare Church]]
- [[file:mount-celva.org][Mount Celva]]
  
*** Map

If you are on a graphical browser, you can view a map of the
locations below.

#+BEGIN_EXPORT html
  <iframe width="100%" height="400px" frameborder="0" allowfullscreen allow="geolocation" src="//umap.openstreetmap.fr/en/map/untitled-map_1203148?scaleControl=true&miniMap=false&scrollWheelZoom=true&zoomControl=true&editMode=disabled&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=none&captionBar=false&captionMenus=true#14/46.0689/11.1224"></iframe><p><a href="//umap.openstreetmap.fr/en/map/untitled-map_1203148?scaleControl=true&miniMap=false&scrollWheelZoom=true&zoomControl=true&editMode=disabled&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=none&captionBar=false&captionMenus=true#14/46.0689/11.1224">See full screen</a></p>
#+END_EXPORT

---

Travel: [[file:../reading.org][Reading]], [[file:../../theindex.org][Index]]
