#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:chronological.org][Chronological]] >

* High School
#+INDEX: Giovanni's Diary!Autobiography!High School 2

Yet, I was a very shy and introverted person, and quite socially
awkward and isolated. On my last year of high school I began pushing
myself out of my comfort zone and partecipated in some activities like
[[file:../ephemeris/2025-05-14.org][theater]], creative writing and [[https://www.youtube.com/watch?v=JHoOj4z4-qs][public speaking]]. This was the bravest
decision of my life and it would change its course. Slowly, I
started getting used to going outside of my room and being surrounded
by other people, something I was greatly struggling (and still do
sometimes). I also met F which helped me a lot with my self confidence
and isolation.

I also travelled by myself for the fist time: I went to [[file:../stash/photography/sicily.org][Sicily]] several
times, I still remember those days vividly, then to Florence for a
performance and to Turin for the national final of the cybersecurity
olimpiads. I graduated with top marks and I started writing my diary.

I [[file:university.org][continued my studies]] in Computer Science in Trento, in the beautiful
Italian Alps.

-----

> [[file:early-life.org][Early Life]] > [[file:middle-school.org][Middle School]] > [[file:high-school.org][High School 1]] > High School 2 > [[file:university.org][University]] > ...
