#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:chronological.org][Chronological]] >

* High School
#+INDEX: Giovanni's Diary!Autobiography!High School

I attended a Liceo Scientifico in my city, which focuses on scientific
subjects.

Out of frustration, I decided to quit youtube since my perfectionism
was making me anxious and depressed: everything had to be perfect and
I could not allow myself any errors. I started playing some other
games instead like Skyrim and Dark Souls 1 (fun story, I broke a
monitor while playing DS1).

During this time I participated in several programming Olympiads and
cybersecurity competitions. I was doing good in the competitions,
reaching nationals every time.  More specifically, I participated in
the cyberchallenge which is an university CTF competition and I
arrived first place and competed in the nationals. During this time, I
met probably the greatest programmer I know, Leonardo Taccari, which
is part of the board of NetBSD and a true UNIX fellow. I asked him
suggestions about books to learn UNIX and he suggested me [[file:../programming/apue.org]["Advanced
Programming in the Unix Environment"]], a book that I bought and read
all the way in the following months. Later this book would influence
me to dig deeper in operating systems and UNIX kernels and stay close
to the operating systems world. It was clear to me I wanted to be a
[[file:../programming/programming.org][computer scientist]].

[[file:high-school-2.org][Continue]]

-----

> [[file:early-life.org][Early Life]] > [[file:middle-school.org][Middle School]] > High School 1 > [[file:high-school-2.org][High School 2]] > [[file:university.org][University]] > ...
