#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:chronological.org][Chronological]] >

* High School
#+INDEX: Giovanni's Diary!Autobiography!High School

I attended the Liceo Scientifico "Enrico Medi" where I participated in
programming Olympiads and cybersecurity competitions. I was doing good
in the competitions, reaching nationals every time and this made me
choose the path ahead: I wanted to be a [[file:../programming/programming.org][computer scientist]].  In
particular, I participated in the cyberchallenge which is an
university CTF competition and I arrived first place and competed in
the nationals. During this time, I met probably the greatest
programmer I know, Leonardo Taccari, which is part of the board of
NetBSD and a true UNIX fellow. I asked him suggestions about books to
learn UNIX and he suggested me "Advanced Programming in the Unix
Environment", a book that I bought and read all the way in the
following months. Later this book would influence me to dig deeper in
operating systems and UNIX kernels and stay close to the operating
systems world.

Yet, I was a very shy and introverted person. On my last year of high
school I began pushing myself out of my comfort zone and participating
in some activities like [[file:../ephemeris/2025-05-14.org][theater]] courses. This was the bravest decision
of my life and It would change the course of it. Slowly, I started
getting used to going outside of my room and being surrounded by other
people, something I was greatly struggling (and still do sometimes). I
also met F which helped me a lot with my self confidence and
isolation.

The last year I did creative writing, public speaking and theater. I
also travelled by myself for the fist time: I went to [[file:../stash/photography/sicily.org][Sicily]] several
times, I still remember those days vividly, then to Florence for a
performance and to Turin for the national final of the cybersecurity
olimpiads. I graduated with top marks and I started writing my diary.

I [[file:university.org][continued my studies]] in Computer Science in Trento, in the Italian
Alps.

-----

> [[file:early-life.org][Early Life]] > [[file:middle-school.org][Middle School]] > High School > [[file:university.org][University]] > ...
