#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:chronological.org][Chronological]] >

* Middle School
#+INDEX: Giovanni's Diary!Autobiography!Middle School

After a family trip in northern Italy I remember I was curious about
"how do people make computer programs", so I asked my dad, which is
not an expert, but he hinted that they were made with programming
languages "like C++". When I came back home I started looking what was
this "c++".  I downloaded dev-c++ and began writing classic programs
like text based games with decision trees. I [[file:old-programs-cpp.org][still have many of those]].

When I was about 13 I began watching youtube videos on [[https://youtu.be/6AZmhj82W-8?si=AkQrqeGK4nUhTl6F][how to make
videogames with Unity]] engine and I made my own little horror
games. I remember spending most of my wake time watching these videos,
programming in C# and playing either minecraft of The Sims 1.

During that time I wanted to [[file:../stash/youtube.org][make youtube videos myself]] so I started a
[[https://www.youtube.com/@San7oS][gaming channel]] where I would play minecraft and other games. This was
a long yourney: I learned things like redstone, video editing and
recording, photoshop and much more. I was really invested in my
minecraft world and I remember this period as an happy one.

I also started playing the [[file:../stash/piano.org][piano]]! Now it was time for me to go to [[file:high-school.org][high
school]].

-----

> [[file:early-life.org][Early Life]] > Middle School > [[file:high-school.org][High School 1]] > [[file:high-school-2.org][High School 2]] > [[file:university.org][University]] - ...
