#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:chronological.org][Chronological]] >

* Middle School
#+INDEX: Giovanni's Diary!Autobiography!Middle School

When I was about 13 I began watching youtube videos on [[https://youtu.be/6AZmhj82W-8?si=AkQrqeGK4nUhTl6F][how to make
videogames with Unity]] engine and I made my own little horror
games. I remember spending most of my wake time watching these videos,
programmingin C# and playing either minecraft of The Sims 1.

During the same time I wanted to make youtube videos myself so I
started a [[https://www.youtube.com/@San7oS][gaming channel]] where I would play minecraft and other
games. This was a crazy yourney: I learned so many thing like advanced
redstone, video editing and recording, creating miniatures with
photoshop and so many other things. I was really invested in my
minecraft world and I remember this period as an happy one because I
had always so many redstone projects in mind and I was working on
something that made me proud. However, even good things come to an end
and by 2019 my perfectionism was making me anxious and depressed
because everything had to be perfect and I could not allow myself any
errors. I decided to quit the channel out of frustration and play
other games like Dark Souls 1 and Skyrim.

After a family trip in northern Italy I remember I was curious about
"how do people make computer programs", so I asked my dad, which is
not an expert, but he hinted that they were made with programming
languages "like C++". When I came back home I started looking what was
this "c++".  I downloaded dev-c++ and began writing classic programs
like text based games with decision trees. I [[file:old-programs-cpp.org][still have many of those]].

It was time for me to go to [[file:high-school.org][high school]].

-----

> [[file:early-life.org][Early Life]] > Middle School > [[file:high-school.org][High School]] > [[file:university.org][University]] - ...
