#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:chronological.org][Chronological]] >

* University
#+INDEX: Giovanni's Diary!Autobiography!University

The first year of university I was feeling a lot of pressure and
anxiety, yet I managed to be stoic about It and kept pushing
through. At the end of January 2023 I travelled across Europe alone
with [[file:../stash/photography/interrail.org][interrail]], this was meant as a voyage of self discovery and I
wrote hundreds of pages of my diary. It was a period where I felt
stuck and I was uncertain about my future. In the second half of the
year I began [[file:../stash/volunteering.org][volunteering]] in a local hiking association. I was
organizing hikes for groups of kids, I felt a lot of responsibility
but I also had a lot of fun. I learned a lot. In the summer I went one
week in the mountains and I joined a folk dances group.

In my second year at university was a difficult year, by the end of it
I went through a big breakdown that would follow me for another
year. I decided to focus fully on studying computer science, which is
what I have always liked. I began intermediate projects like a [[https://github.com/San7o/Brenta-Engine][game
engine]] and a [[https://github.com/San7o/Baldo-Scanner][vulnerability scanner]] and I got into Linux kernel
development and cloud computing.

To be continued...

-----

> [[file:early-life.org][Early Life]] > [[file:middle-school.org][Middle School]] > [[file:high-school.org][High School 1]] > [[file:high-school-2.org][High School 2]] > University - ...
