#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] > [[file:economics.org][Economics]] >

* 15.401 - Finance Theory @ MIT
#+INDEX: Giovanni's Diary!Reading!Economics!Finance Theory

Here are my notes on Finance Theory I from professor Andrew Lo at
MIT. All the lessons can be watched [[https://www.youtube.com/watch?v=HdHlfiOAJyE][on youtube]] for free.

I recently noticed that many people around me (digitally) were talking
about finance, however I do not have a framework for thinking of
finance because of my background. I am a programmer, a scientist, but
I was never introduced to the subject of economy. I never had a class
in economy in my education so I consider myself an humble beginner, I
started reading [[file:henry-hazltt-economics-in-one-lesson.org][Economics in one lesson]] by Henry Hazltt which got me
interested to learn more, so I began watching these lessons on
youtube.

** Introduction

The introductory lesson from Andrew Lo left me both speechless and
uncomfortable. The highlight of the lecture was an auction performed
in class, which went as follows. The teacher put two boxes on his
table and randomly selected one, just a tiny little box. He then asked
the students how much were they willing to pay for that box.  The
auction was real and he expected to be paid in cash, so students had
to say amounts that they would actually pay with their money. One
dollar, two, five, 15... by the end the box was sold for 45$. The
teacher took a moment to reflect on the fact that nobody knew what
was in the box, or what his value was. Nobody could come closer to
inspect the object, yet they bet on Its value. Well, now the value
of the box was 45$, they agreed on this price and so be it. What
the class just did is called price discovery, and It is something
that an economist has to do constantly.

On my logical mind I was like "they are just choosing a random number
and that Its his value, what a bs, this is so stupid". And I though
about how do people value art pieces, or luxury items, or many other
things. This makes no sense yet the world works like this, I thought.

Moving on, the teacher writes about the six fundamental principles
of finance, namely:

- There Is No Such Thing As A Free Lunch
- Other Things Equal, Individuals
  - Prefer more money to less (non-satiation)
  - Prefer money now to later (impatience)
  - Prefer to avoid risk (risk aversion)
- All Agents Act To Further Their Own Self-Interest
- Financial Market Prices Shift to Equalize Supply and Demand
- Financial Markets Are Highly Adaptive and Competitive
- Risk-Sharing and Frictions Are Central to Financial Innovation

The teacher explains to the class that all business activities reduce
to two functions: valuation of assets and management of assets. Yet,
once you are able to evaluate assets, managing becomes really easy.
Just to feel smarter, the economist threw an equation as if they
wanted to act like mathematicians.

#+begin_src
  Objecives + Valuations -> Decision
#+end_src

Another random equation is the definition of finance:

#+begin_src
  Mathematics + $$$ = Finance
#+end_src

From this equation we also derive that:

#+begin_src
  Mathematics = Finance - $$$
#+end_src

-----

Travel: [[file:economics.org][Economics]], [[file:../../theindex.org][Index]] 
