#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] > [[file:economics.org][Economics]] >

* Economics in One Lesson - Henry Hazlitt
#+INDEX: Giovanni's Diary!Reading!Economics!Economics in One Lesson

I find this book interesting and intellectually stimulating, I have
heard It is a classic in economics and one of the best introductions
to the field. "Economics in One Lesson" covers the basic ideas in
economics, first by stating the key points and then taking time to
elaborate on them.

** The First Lesson

The "First Lesson" opens up by stating how economics is hunted by
fallacies, those are created because of selfish interests and the
tendency of men to see only the immediate effects of a given policy,
or only on a special group.

#+BEGIN_QUOTE
The art of economics consists in looking not merely at the immediate
but at the longer effects of any act or policy; it consists in tracing
the consequences of that policy not merely for one group but for all
groups.
#+END_QUOTE

By considering only the short term effects of a policy we may reach
reasonable conclusions, however we may reach other conclusions by
considering long term effects, or maybe another population. Such is
the economics's fallacy.

** The broken window

The book proceeds by giving an important example that keeps appearing
in many occasions and in different forms, the example goes as
follow. Imagine that a young gangster happens to break the window of a
shop. Obviously the shop owner is furious but the guy manages to
escape and now the shop owner has to pay the damages. You may think
that this is a great misfortune for the shop owner, however you start
elaborating on the event. The shop owner now has to pay 50$ to a glass
manufacturing company, which in turns has to pay the materials and the
transportation to another company, which in turns has to pay some
other people and so on.  By breaking the window, the gangster made
more money circulate, provided money and employment in circles, the
logic conclusion then would be to say that the boy is not a criminal,
but a public benefactor.

However, the shop owner will have 50$ less which he wanted to use for
a new suit. Now he has to choose between the window and the suit,
preventing money circulating to the suit maker. At the end, no new
employment has been added: where employment was created on one area
(the window industry), the same amount was removed from another (the
suit making industry). Yet, many people don't see what could have been,
instead they focus on what they see now which is often misleading.

This broken window fallacy shows itself again and again in the history
of economics, such as during a war when everybody talks about the new
jobs that the war economy open up, forgetting about all the others
that It closes. In particular, during war time you will see a
particular diversion of demand to some particular products over
others. During reconstruction, Europe had a lot of demand and manpower
to rebuild new houses, and less productive capacity for everything
else.

** Government spending

The author proceeds by using the same broken window fallacy to explain
how government spending is harmful and hostile for an economy. The
main idea is similar to what was discussed in the wartime fallacy: if
a government uses public money to build a bridge, people may believe
that this creates jobs and opportunities, but in fact It just moves
jobs from one place to another. The same applies to all types of
government spending and to taxes: when the government is taking taxes,
It is like breaking the window. Now each citizen has less money to
spend and create employment, opportunities were only moved around and
the argument that the government is creating new jobs is unreasonable.

But there is a deeper argument against government spending, in
particular government "encouragement" to business, and that is
**risk**. When a private company, say a bank, lands money on some
company or person, they take the risk of the investment and will be
very careful with whom they have business with. Often this is not the
case with government spending, and all the risk of bad investments
falls on the citizens.

The book gives the example of two farmers: one really respected and
with a good track record of success, and another poor with very
little to show. They both want to buy a terrain to increase their
production, so they ask for money. A bank would judge the situation in
favor of the successful farmer since It has less risk and the
investment has more chances to pay off. The government instead does
different judgments, It may think that giving money to the poor
person will make him a productive member of society. This happens
everywhere and the risk falls completely on the citizens, not only
their money where withdrawn from them through takes, but additionally
they are spent poorly.

Moreover, private lenders are selected by cruel market test, If they
make mistakes they loose their money and have no more money to lend,
they act really carefully. Instead, government lenders "are either
those who have passed civil service examinations, and know how to
answer hypothetical questions hypothetically, or they are those who
can give the most plausible reasons for making loans and the most
plausible explanations of why it wasn’t their fault that the loans
failed". In short, government loans will reduce production, not
increase It.

** Machines will remove jobs

An entire chapter was dedicated to the misconception that technology
will replace human workers, something that has come time and time
again and proven wrong every time. The argument against this is noting
the fact that machines will make a job faster or cheaper, or both.
This in turn will make more money for the manufacturer because of cut
costs or increased production. And obviously the manufacturer has to
buy the machines, and they are made of other parts from other
companies: employment is moved from one group to another.

Therefore, the argument that technology will replace workers is wrong,
furthermore the manufacturer / employer can choose to spend the
additional revenue either on investing on his business, on other
businesses or buying new machinery, which increases employment on
those areas.

To be continued...

-----

Travel: [[file:economics.org][Economics]], [[file:../../theindex.org][Index]] 
