#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] > [[file:economics.org][Economics]] >

* Itermediate Micro Economics - Hal. R. Varian
#+INDEX: Giovanni's Diary!Reading!Economics!Intermediate Micro Economics

* Chapter 1: The Market

** Models

Economics proceeds by developing *models* of social phenomena, which
are a simplified representation of reality.

For example, let use consider the market for apartments in a
medium-size mid-western college town. We may suppose that the
apartments closer to the university are more desired since people have
to walk less to go to the university, we will only consider this
distance in out model, up to a maximum distance.

** Exogenous and endogenous variables

Our model does not cover the apartments outside of this distance or
ring, and we say that their price is an *exogenous variable*, while
the price of the closer apartments is an *endogenous variable*.

** Optimization and equilibrium principle

Whenever we try to explain the behavior of human being we need to
have a framework on which our analysis can be based. We will follow
two simple principles:

- *the optimization principle*: people try to choose the best
  patterns of consumption that they can afford
- *the equilibrium principle*: prices adjust until the amount that
  people demand of something is equal to the amount that is supplied.

The first principle is almost a tautology, indeed it seems
unreasonable that people would not try to get things that they don't
want. The second is a bit more problematic, it may happen that supply
and demand are not compatible, but for most cases they are. For
example, the price of apartments is fairly stable over a short
time-frame. We will ignore long time frames in this initial analysis.

** Reservation price

We call the *reservation price* a person's maximum willingness to
pay for something. It is the highest price that a given person will
accept and still purchase the good.

In our example, the number of apartments that will be rented at a
given price $p^*$ will just be the number of people who have a
reservation price greater than or equal to $p^*$. For if the market
price is $p^*$, then everyone who is willing to pay at lest $p^*$ for
an apartment will want an apartment in the inner ring, and everyone
who is not willing to pay $p^*$ will choose to live in the outer ring.

** The demand curve

The *demand curve* is a plot showing the price and the number of
people who are willing to pay that price or more. Since data is
discrete, that would be the best curve that fits the data.

** Competitive market

We refer to a *competitive market* the situation where there are
many independent landlords who are each out to rent their apartments
for the highest price the market will bear.

** The supply curve

Let us now consider the case where there are many landlords who all
operate independently. If all landlords are trying to do the best they
can and if the renters are fully informed about the prices the
landlords charge, then the equilibrium price of all apartments in the
inner ring must be the same. The argument is not difficult. Suppose
instead that there is some high price $p_h$ and some low price $p_l$
being charged for apartments. The people who are renting their
apartments for a high price could go to a landlord renting for a low
price and offer to pay a rent somewhere between $p_h$ and $p_l$.
A transaction at such a price would make both the renter and the
landlord better off. To the extent that all parties are seeking to
further their own interests and are aware of the alternative prices
being charged, a situation with different prices being charged for the
same good cannot persist in equilibrium.

In out case, considering a short timeframe that does not account for
new houses being built, the *supply curve* would be a vertical
line. Whatever price is being charged, the same number of apartments
will be rented.

** Market equilibrium

We refer to the *equilibrium price* $p^*$ as the price where the
quantity of apartments demanded equals the quantity supplied. At this
price, each consumer who is willing to pay at least $p^*$ is able to
find an apartment to rent, and each landlord will be able to rent
apartments at the going market price. Neither the consumers nor the
landlords have any readon to change their behaviour, hence the term
_equilibrium_.

** Comparative statics

*Comparative statics* is the study of the behaviour of the equilibrium
price when various aspects of the market change. Here we study only
the change from one equilibra to another, hence the term _static_, we
do not consider how that movement takes place for now.

As an exercise, suppose that a developer decides to turn several of
the apartments into condominiums, what will happen to the price of the
remaining apartments? If we suppose that the people who where renting
the apartments will buy them, then the demand for apartments will have
been reduces as much as the supply, so the equilibrium price remains
unchanged.

Let's consider another example, where the city council decides that
there should be a tax on apartments of 50 dollars a year, what will
this do to the price of apartments? We observe that the supply curve
doesn't change as there are just as many apartments after the tax as
before the tax, and the demand curve doesn't change either, therefore
the price does not change as a result of the tax. In essence, the the
demand does not change, the landlords cannot raise the price to
compensate for the tax, or not enough people would afford to occuply
the apartments and the landlords will not be able to get the rented
price. Note that we are assuming that the supply of apartments remains
fixed.

** Other ways to allocate apartments

So far we have assumed a competitive market. This is not the only type
of markets, here are other ways:

- *the discriminating monopolist*: here we consider a situation where
  there is only one dominant landlord who own all of the apartments
  (or a number of individual landlords cooperating) also known as a
  *monopoly*. Suppose the landlord could decide to auction them off
  one by one to the highest bidders, in this situation exactly the
  same people will get the apartments as in the case of the market
  solution, and the last person to rent an apartment pays the price
  $p^*$. The discriminating monopolist attempts to maximize his own
  profits leading to the same allocation of apartments as a
  competitive market but with different amounts paid by each person.
- *the ordinary monopolist*: what if the monopolist wwere forced to
  rent all apartments at the same price?If he chooses a low price he
  will rent more apartments but he may end up making less money than
  if he sets a higher price. What he will do instead is not to rent
  all apartments, but to rent only a fraction of them so that it
  maximizes the provit from the highest bidders.
- *rent control*: let us consider the case where the city imposes a
  maximum rent that can be charged for apartments $p_{max}$. Suppose
  $p_{max} < p^*$, then we would have a situation of *eccess demand*
  where there are more people who are willing to rent apartments at
  $p_{max}$. Who gets the apartment is outside the scope of the model.

** Pareto Efficiency

To compare different economics institutions, we introduce the *Pareto
efficiency* which is defined in the following way: if we can find a
way to make some people better off without making anybody else worse
off, we have a *Pareto improvement*. If an allocation allows a Pareto
improvement, it is called *Pareto inefficient*; if an allocation is
such that no Pareto improvements are possible, it is called *Pareto
efficient*. The idea is that, if there is a way to make someone better
off without hurting anyone else, why not do it?

* Chapter 2: Budget Constraint

In this chapter, we will examine how to describe what a consumer can
afford.

** The budget constraint

We define a *consumption budle* $(x_1, x_2)$ as a pair representing
how much the consumer is choosing to consume of good $1$, $x_1$, and
how much the consumer is choosing to consume of good $2$, $x_2$. We
suppose that we can observe the prices of the two goods $(p_1, p_2)$
and the amount of money the consumer has to spend $m$

Then, a *budget constraint* is:

$$
p_1 x_1 + p_2 x_2 \le m
$$

where $p_1 x_1$ is the amount of money the consumer is spending on
good $1$, and $p_2x_2$ for good $2$.

The consumption bundle may be generalized as such. If we are
interested in studying a consumer's demand for milk, we might let
$x_1$ measure his or her consumption of milk and let $x_2$ stand for
everything else the consumer might want to consume in dollars, so $p_2
= 1$. The budget constraint would then look like:

$$p_1x_1 + x_2 \le m$$

which is a special case of the original budget constraint, so
everything that applies in the general case also applies here.

** Budget line

The *budget line* is the set of bundles that cost exactly $m$:

$$p_1x_1 + p_2x_2 = m$$

These are the bundles of goods that just exhaust the consumer's
income, which is a line. We say that the derivative of the line is the
*opportunity cost* of consuming good $1$. In order to consume more of
good $1$ you have to give up some consumption of good $2$ which is
measured by the slope of the budget line.

-----

Travel: [[file:economics.org][Economics]], [[file:../../theindex.org][Index]] 
