* Examples

Some text samples from interesting things I read.

** Poetry

*** To the unknown journeyman

#+begin_quote
To the unknown journeyman
I promise to show courage
in upholding my vows

What is an adventure
if not the commitment
to keep going?
#+end_quote

By Protesilaos Stavrou, 2025-08-11, [[https://protesilaos.com/poems/2025-08-11-unknown-journeyman/][original link]].

Truly beautiful and powerful words from Prot, as always. I feel
greatly moved by this poem.

From Wikipedia, a journeyman is "a worker, skilled in a given building trade or
craft, who has successfully completed an official apprenticeship
qualification.". He is someone that showed dedication and fought through
adversities to master his skill: someone can can be looked up to. Yet there
are many "unknown" journeymen, especially in the world of programming, there
are so many professionals that are doing excellent and critical work but are
greatly under-recognized and underappreciated (maybe Prod is thinking of his
condition, and the one of other maintainers).

Someone that mastered their skills can motivate us into working harder and
harder. It surely does for me. He made a promise to himself, and so do I, to
never give up.

The second part of the poem explores this idea, and it words it beautifully.

I find a deep stoic meaning in this poem, to keep going through life
nevertheless.

*** Blue Flower

#+begin_quote
Blue flower — wonderous flower,
You’ll wonder no more.
Distinguished from the field;
Still the field is power.

Be thee a hole in Earth, for:
Weather comes like the ocean.
Delicate flower, grounded by rhythms;
Your weary soul drags its flesh to bed.

Lucky flower — uncursed flower,
Parted your lips and was heard;
And lashing had fun, you never
Knew better, blue flower.
#+end_quote

I really like the repetition of flower in the first sentence.


** Short Stories

*** Hills Like White Elephants by Ernest Hemingway

[[https://americanliterature.com/author/ernest-hemingway/short-story/hills-like-white-elephants][link]]

Notes: Iceberg theory (theory of omission), strong symbolism in the settings

Intro:

#+begin_src

The hills across the valley of the Ebro were long and white. On this side there
was no shade and no trees and the station was between two lines of rails in
the sun. Close against the side of the station there was the warm shadow of
the building and a curtain, made of strings of bamboo beads, hung across the
open door into the bar, to keep out flies. The American and the girl with
him sat at a table in the shade, outside the building. It was very hot and
the express from Barcelona would come in forty minutes. It stopped at this
junction for two minutes and went on to Madrid.

#+end_src

Notice how the scene is zoomed in from far away.

*** Girl by Jamaica Kincaid

[[https://moodle.carmelunified.org/moodle/pluginfile.php/110773/mod_resource/content/1/Girl%20by%20Jamaica%20Kincaid.pdf][link]]

This makes you feel like the character.

*** The Paper Menagerie by Ken Liu

[[https://estabrookpto.org/wp-content/uploads/2024/09/88369-the-paper-menageriebykenliu.pdf][link]]

Very emotional story.

[[file:./index.org][back]]
