* Wilfred in Venice

Challenge theme: You just lost your hotel key, and you're now locked out of your
room. It's the middle of the night, and your phone is on 1%. Write a comedic
scene of you running around, trying to find the key. 200-500 words.

---

The city of Venice never sleeps during summer nights. Tourists flood the narrow
streets, entertained by shows of dances and magic, bright yellow lights, and a
smell of alcohol. Wilfred, a tall men in his 60s with a tired face that had
not aged well, had enough for the day. He wanted to make the most out of his
short and rare trips, so he carefully optimized the route to see as many
landmarks as physically possible despite his poor fitness. He ran here
and there the entire day with just one or two breaks, up until the night.

Back at the hotel, a very characteristic old building, Wilfred had just enough
energy to fall into his bed and dream about his next day. After stepping off
the Gondola right next to the Hotel's iron gate, and admiring the fine frame
around it, he was limping towards the white stairs just on his front. Up two
floors, another gate and a tight corridor, with a glimmer of light he was
confronted with his room's door. He could finally get some rest.

Wilfred put his plastic bag of souvenirs on the floor (a bunch of magnets and a
fancy carnival mask) so he could put his left hand into his jeans pocket and
get the old fat copper key. After a moment, he noticed something was off. He
focused on the touch of his fingers: the crumpled receipt of the cappuccino
he got that morning, a melted chocolate candy gifted by his coworker last week
(which he totally forgot about), a little hole through the rough fabric of his
jeans. But something was missing, the key.

Wilfred stayed completely still for a few seconds, rigid like a statue, barely
breathing. With a quick movement he put his other hand on the right pocket,
looking for the key. Negative. So he immediately stared at the plastic bag,
dumping all its contents on the floor. He checked again his left pocket, still
nothing. Then checked the bag again. Did he check his right pocket? Yes he
did, but he checked another time. And the bag again. But there were no signs
of the key.

With barely any energy, he ran through the corridor and stairs, touching the
floor with both his palms, trying to recognize the shape of the key. Did he
lose the key on his way up the stairs? Or back at the gate? Or before that,
when he was running around in Piazza San Marco? Maybe he was robbed by one of
many pickpockets roaming the city, that could explain the situation. Or maybe
he placed the key somewhere and forgot it? Unlikely but plausible. What did the
key look like? Maybe he just missed it, so he went back again through the
stairs and the corridor towards the door and everything he left on the floor.
He checked his pockets again, left and right.

Tired and defeated, he could only sit down and think about this tomorrow. At
this point, all Wilfred could think about was sleeping. So as he lay down on
the ground, he could feel something on his butt, but he had no more energy to
care anymore, as he completely fainted into a deep sleep. Yes, that was the
key.

---

04 August 2026

[[file:./index.org][back]]
