* Travelling gnome

Challenge: At a family getaway, in a cozy cottage, strange noises could be
heard from the garden. You go to inspect the noises and find two garden gnomes
talking. Write a dialogue scene of the two bickering about something. No word
limit.

---

"So, how is the world? Please tell me Bilbo, I want to know!" Lampy cried as he
was leaning towards Bilbo, almost losing balance on his tiny feet.

"The world.. mm, it is much bigger than I thought." Bilbo replied, then paused
to look at his boots, then up, and finally continued: "Back in my garden,
everything is still and quiet, but out there, everything is in motion,
everything keeps changing"

"Like.. like how trees change colors with the seasons?" a puzzled Lampy asked.

"Yes, sort of." - another pause - "I noticed humans do too. Miss Hilton looks
totally different sometimes: she wears different colors during the day, and
when she talks to another human she shows her teeth and touches her hair; I
saw her crying once. She takes me to visit places she travels to, although she
doesn't always have a plan for the day."

"Is Miss Hilton the human from the window?" Lampy whispered as he wondered about
the girl sitting on one of the windows, presumably sleeping.

"Yes, that's her. But, you see, not all humans are alike. Did you know that some
of them look like gnomes too? I saw them playing with a ball or with a
hula-hoop!"

"Woo.. what is a hula-hoop Bilbo?"

"It is a kind of plastic circle that humans like to play with, for example by
making it spin over their body; they play with all sorts of things, I think it
may be some form of ritual. But the taller humans do not enjoy these things,
they seem very serious all the time."

"Why are they so serious?"

"I don't know, maybe their life is a tough one. Out there it is not always as
peaceful as in my garden." Bilbo replied, turning his head slightly towards
Miss Hilton.

"Do you miss your garden sometimes?"

"Yes Lampy, yes, I miss my garden. I miss the smell, the looks of the shadow from
the tree. Eventually I will come back, but, for now, I want to explore some
more."

---

04 September 2026

[[file:./index.org][back]]
