* Tidal Wave

Challenge: The ocean is a place of relaxation and peace. All of the sudden, you
see a tidal wave coming towards you. Write a journal entry of 250-600 words
detailing the event.

---

Up it rose, touching the sun, eating the sky, still rising, rising. Some fleeing
and some paralyzed, we were powerless. The wave marched straight to the beach,
with nowhere to go but over our faces, through the body, out the back. We were
in the front line, waiting and praying while confronting the wall.

Behind, my kids were playing with the sand and a little ball. Over the last two
days, they had carefully crafted a rally circuit for the shiny ball,
with ups and downs and tight corners. The most artistic of the three had
proudly built castles and bridges in fine detail, under the watchful eye of
the oldest, who supervised the construction activities. They did not see the
wave, or maybe they did but they did not care, still chasing the dream circuit.

But I could not help.

With a loud crash the wave dove into me, blinding my eyes, filling my ears,
shutting my mouth.

I fought at my best, for what it was worth, clinging to hope.

In a moment, my body was floating like an astronaut in the salty space, losing
sense of up or down, left or right.

As I was propelled forward, flashes of the peaceful morning rushed through my
mind: the same familiar people you would always find relaxing on the ground,
the same young bartender who had been there most weekends since the start of
the season, the same hot sun and blue sky.

Maybe tomorrow would be another day like any other, with the same bartender, that
same sky, and everyone will just forget about that wave, like we often do.

---

05 August 2026

[[file:./index.org][back]]
