#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../subjects.org][Subjects]] > [[file:programming.org][Programming]] >

* Free as in Freedom
#+INDEX: Giovanni's Diary!Programming!Free as in Freedom

As a programmer, I believe in the principles of free software:

- The freedom to run the program as you wish, for any purpose
- The freedom to study how the program works, and change it so it does
  your computing as you wish. Access to the source code is a
  precondition for this.
- The freedom to redistribute copies so you can help others.
- The freedom to distribute copies of your modified versions to
  others. By doing this you can give the whole community a chance to
  benefit from your changes. Access to the source code is a
  precondition for this.

I always tend towards free and open source software for my personal
use, reducing the amount of propretary technologies to its minimum.

Living in a free software world is completely doable. Linux (or BSDs)
are great and powerful operating systems. You have the freedom to
manage your own system the way you want: use a FOSS file editor (vim,
emacs, nano), window manager (i3, dwm...), editing software (gimp,
krita, kdenlive), you can self host open source services on your
machine to manage photos or websites. And many more.

We are full of great FOSS software and it is improving every day
thanks to the great effort of the community.

-----

Travel: [[file:programming.org][Programming]], [[file:../theindex.org][Index]] 
