#+startup: content indent

[[file:../index.org][Giovanni's Diary]] >

* Programming
#+INDEX: Giovanni's Diary!Programming



Programming is my main occupation and *passion*. I am particularly
interested in *operating systems* (UNIX and friends). I have worked
on many projects, mostly system level stuff. You can
find my code on my [[https://github.com/San7o/][github]] profile. I maintain a list of my
[[file:repositories.org][public repositories]] to get a tour of what I have been working on.

I am currently developing an *eBPF + kubernetes* application to log
file accesses in a [[file:./kubernetes/kubernetes.org][kubernetes]] cluster.

I do all my reading, writing and coding in [[file:emacs/emacs.org][emacs]] on [[file:./linux/linux.org][Linux]], currently
on Fedora but I am a big Linux From Scratch user. I often like doing
[[file:offline-programming.org][offline programming]] sessions.

Get notified on my programming diary via RSS [[file:../feeds/feedProgramming.rss][here]].

- [[file:support-vector-machines.org][Support Vector Machines]]

*** Wishlist

Check out future [[file:wishlist.org][projects]] I have in mind.

-----

Travel: [[file:../index.org][Giovanni's Diary]], [[file:../theindex.org][Index]]
