#+startup: content indent

[[file:../index.org][Giovanni's Diary]] >

* Programming
#+INDEX: Giovanni's Diary!Programming

Computer science is my main area of expertise. I am particularly
interested in *UNIX operating systems* and I am a strong supporter of
[[file:free-as-in-freedom.org][the free software movement]]. I have worked on many projects, you can
find my code on my [[https://github.com/San7o/][github]] profile; I maintain a list of my [[file:repositories.org][public
repositories]] so you can get a tour of what I have been working on.

I am currently developing an *eBPF + kubernetes* application to log
file accesses in a [[file:./kubernetes/kubernetes.org][kubernetes]] cluster.

I do all my reading, writing and coding in [[file:emacs/emacs.org][emacs]] on [[file:./linux/linux.org][Linux]], currently
on Fedora but I am a big [[file:linux/linux-from-scratch.org][Linux From Scratch]] user. Here is my current
[[file:setup.org][setup]].

Get notified on my programming diary via RSS [[file:../feeds/feedProgramming.rss][here]].

- [[file:notes/notes.org][Public Notes]]
- [[file:contributing-to-openstreetmap.org][Contributing to Openstreetmap]]
- [[file:root-a-samsung-galaxy-j5.org][Root a Samsung Galaxy j5]]
- [[file:offline-programming.org][Offline Programming]]
- [[file:cv.org][CV]]
  
*** Wishlist

Check out future [[file:wishlist.org][projects]] I have in mind.

-----

Travel: [[file:../index.org][Giovanni's Diary]], [[file:../theindex.org][Index]]
