#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../subjects.org][Subjects]] > [[file:programming.org][Programming]] >

* UNIX
#+INDEX: Giovanni's Diary!Programming!UNIX

The UNIX philosophy and culture has been really influential to my
growth as a programmer.

It all boils down to KISS:

> Keep It Simple, Stupid!

[[https://en.wikipedia.org/wiki/Douglas_McIlroy][Douglas McIlroy]] documents the philosophy in the Bell System Technical
Journal as follows:

1. Make each program do one thing well. To do a new job, build afresh
   rather than complicate old programs by adding new "features".
2. Expect the output of every program to become the input to another,
   as yet unknown, program. Don't clutter output with extraneous
   information. Avoid stringently columnar or binary input
   formats. Don't insist on interactive input.
3. Design and build software, even operating systems, to be tried
   early, ideally within weeks. Don't hesitate to throw away the
   clumsy parts and rebuild them.
4. Use tools in preference to unskilled help to lighten a programming
   task, even if you have to detour to build the tools and expect to
   throw some of them out after you've finished using them.

As [[https://cscie28.dce.harvard.edu/reference/programming/unix-esr.html][Eric S. Raymond]] puts It:

> To do the Unix philosophy right [..] you need to _care_. You need to
_play_. You need to be willing to _explore_.

-----

Travel: [[file:programming.org][Programming]], [[file:../theindex.org][Index]] 
