* USB for the apocalypse
#+INDEX: Giovanni's Diary!Programming!Usb for the apocalypse

I am preparing an USB stick in case I need to spend a long period of
time offline, with everything I would need to continue to do my usual
stuff. I will set the maximum size to 64GB.

I will need some sort of operating system, and one that I have full
control of and would last forever. For this reasons, something like
debian would be great.

The USB will have two partitions: a bootable one with the linux
distribution and a data one. The data will have the following content:
- Music: A local music directory
- Offline Encyclopedia: download wikipedia sections, right know I have
  computer science, math and history.
- Offline documentation for SDL3, opengl, cairo.
- source code: source of the linux kernel, various desktop utilities
  such as a window manager (dwm), SDL3, cairo.
- compiler for C code (gcc).
- Text Editor (emacs).
- Multimedia libraries: ffmpeg and vlc, libpng
- Other libraries: opengl
- Offline rfc browser (rfc-mode)
  
---

Travel: [[file:offline-programming.org][Offline programming]], [[file:../theindex.org][Index]]
