#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:programming.org][Programming]] >

* Wishlist :programming:
#+INDEX: Giovanni's Diary!Programming!Wishlist

** Coding
*** TODO Simple filesystem inspired by ext2

Write a linux filesystem inspired by ext2, this should be really fun.

*** TODO Write a database

First, write an in memory databse in C like redis as a warmup.
When you feel ready, write a proper databse with permanent
storage.

*** TODO Keep working on the operating system

I really want to work on my own operating system but It takes
a lot of time and I need to find It.

** Blog Posts
*** TODO Benchmark laptop's power consumption

Benchmark my laptop's performance and power consumption before
and after applying the changes I talked about in the power
consumption optimization post under the linux directory.

*** TODO Evaluate linux's 6.14 wine performance

Finally linux 6.14 is out and I can upgrade. The best thing is
that they added new synchronization primitives compatible with
windows so that emulators / translators do not need to emulate
them. This increases FPS by a lot, in one example It reaches
+600%. I use wine / proton sometimes so I am really happy of
this change.

Maybe It would be interesting to do some performance evaluations
and write my findings.

*** TODO tiny-rss

Document =tiny-rss=, my own RSS feed generator once It is ready and
tested.

-----

Travel: [[file:programming.org][Programming]], [[file:../theindex.org][Index]]
