#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../subjects.org][Subjects]] > [[file:programming.org][Programming]] >

* Wishlist :programming:
#+INDEX: Giovanni's Diary!Programming!Wishlist

** Coding

*** TODO Simple filesystem inspired by ext2

Write a linux filesystem inspired by ext2, this should be really fun.

*** TODO Write a database

First, write an in memory database in C like redis as a warm up.
When you feel ready, write a proper database with permanent
storage.

*** TODO Write a container runtime

Write my own OCI compliant container runtime.

*** TODO Keep working on the operating system

I really want to work on my own operating system but It takes
a lot of time and I need to find It.

** Blog Posts

*** TODO Benchmark laptop's power consumption

Benchmark my laptop's performance and power consumption before
and after applying the changes I talked about in the power
consumption optimization post under the linux directory.

*** TODO Creating a local kubernetes cluster

Write a blog post about how to create a local kubernetes cluster,
explaining the work done in Hive.

-----

Travel: [[file:programming.org][Programming]], [[file:../theindex.org][Index]]
