#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:programming.org][Programming]] >

* Wishlist :programming:
#+INDEX: Giovanni's Diary!Programming!Wishlist

** Coding

*** TODO Simple filesystem inspired by ext2

Write a linux filesystem inspired by ext2, this should be really fun.

*** TODO Write a database

First, write an in memory databse in C like redis as a warmup.
When you feel ready, write a proper databse with permanent
storage.

** Blog Posts
*** TODO On AI

Write down my whoughts on using AI, from a philosophical, moral and
practical point of view. I have much to say here

*** TODO What is a variable?

I went on a pretty big tangent a while ago about the question "what
is a variable?". A truly safisfying and correct answer would require
a book probably, I want to write what I have found.

*** TODO tiny-rss

Document =tiny-rss=, my own RSS feed generator once It is ready and
tested.

** Misc

*** TODO Install linux 6.14
Finally linux 6.14 is out and I can upgrade. The best thing is
that they added new syncronization primitives compatible with
windows so that emulators / translators do not need to emulate
them. This increases FPS by a lot, in one example It reaches
+600%. I use wine / proton sometimes so I am really happy of
this change.
Maybe It would be interesting to do some performance evaluations
and write my findings.

*** TODO Install FreeBSD on my laptop
There is an ongoing effort to bring laptop support in FreeBSD.
I want to see If I can help by testing on my hardware and
supporting developers.

-----

Travel: [[file:programming.org][Programming]], [[file:../theindex.org][Index]]
