#+startup: content indent

[[file:../../../index.org][Giovanni's Diary]] > [[file:../../../subjects.org][Subjects]] > [[file:../../programming.org][Programming]] > [[file:../notes.org][Notes]] >

* Introduciton to Machine Learning
#+INDEX: Giovanni's Diary!Programming!Notes!Intro to Machine Learning

This book contains useful notes for students studying for an
introductory course to Machine Learning, or to anyone interested in
the subject. The structure of the book results from my notes during
the "Introduction to Machine Learning" course held by Elisa Ricci at
the University of Trento in the academic year 2024-2025. During the
course, I found myself more interested in the math than what the
course taught, so I dedicated some of my time to understand the math
better and to fill some of the gaps in my education. My final notes
resulted in the book you are reading.

Big thanks to [[https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/][Pattern Recognition and Machine Learning]] by Christopher
Bishop which guided me in my studies.

- [[file:01-basics.org][Machine learning basics]]
- [[file:02-knn.org][K-Nearest Neighbors]]
- [[file:03-linear-models.org][Linear Models]]
- [[file:04-beyond-binary-classification.org][Beyond binary classification]]
- [[file:05-decision-trees.org][Decision trees]]
- [[file:06-gradient-descent.org][Gradient descent]]
- [[file:07-support-vector-machines.org][Support Vector Machines]]
- [[file:08-regularization.org][Regularization]]
- [[file:09-unsupervised-learning.org][Unsupervised learning]]
- [[file:10-clustering.org][Clustering]]
- [[file:11-neural-networks.org][Neural Networks]]
- [[file:12-deep-generative-models.org][Deep Generative Models]]
- [[file:13-diffusion-models.org][Diffusion Models]]
- [[file:14-reinforcement-learning.org][Reinforcement Learning]]
  
-----

Travel: [[file:../notes.org][Notes]], [[file:../../../theindex.org][Index]]
