#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-06-24 - The importance of having genuinely fun
:PROPERTIES:
:RSS: true
:DATE: 24 Jun 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-06-24.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-06-24 - The importance of having genuinely fun

(I am writing this entry the day after since I slept early yesterday)

Lately I have been spending the majority of my time studying for my
last university exams. I have been preparing for these exams for at
least two months without breaks, and until recently I followed all the
lessons diligently. In general, when I study something I want to be
completely immersed in the subject and I want to get as many inputs as
possible: youtube videos, books, exercises, I keep thinking about It
day and night. Hence, I never really take "breaks" from studying, just
change or limit my inputs. It comes no surprise that sometimes I feel
exhausted, so I give myself some minutes off to slow down the pace.

After a while, this routine of studying from morning until I am too
tired is not healthy and I need to take more time off. Lately I went
too far and now I have a great headache and I have problems sleeping,
consequently I don't have a lot of energies during the day and I have
difficulties concentrating. Always thinking about the same things made
my mind kind of stuck, I needed some kind of distraction. To be
totally honest, I am doing other things such as reading a book about
economics and another about hacker culture, I am learning the lean
programming language and in general I have been reading a lot of math
books, or just taking a walk or trying to sleep more. I found these
activities ineffective to "unstuck" my brain, I needed more powerful
distractions that could take me off my studies. So I thought about
video games.

I thought that playing a fast paced, online FPS game would be the
solution. I have not played a game like this in 4+ years and I
wouldn't say I am the type of person to play these types of games. I
also wanted something that could run on very cheap hardware and on
Linux.  After some research, I found [[https://xonotic.org/][xonotic]]: a free classic arena
shooter similar to quake or unreal tournament. I have to say that I
really had a great fun playing this game, I was fully concentrated and
my senses were 100% active in order to react to the fast movement of
the enemies. I haven't felt this adrenaline in a while, additionally
the chat and the soundboards were hilarious and made me laugh. Even if
I was not at the top of the leadeboard, I gave my best and had fun, I
even recorded my matches on a new [[https://www.youtube.com/@Giogames-d6f][youtube channel]].

Playing this game changed my day and I had more energies to do other
things. As someone that really rarely grants himself some time off,
this was a good reset. Most of the time It is difficult to stay
focused on something and I think you should render all distractions
at minimum, that's what I always try to do. Yet a dose of distraction
can also be beneficial, and this experience is a reminder of this.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]] 
