#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-03-24
:PROPERTIES:
:RSS: true
:DATE: 24 Mar 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://san7o.github.io/giovanni-diary/ephemeris/2025-03-24.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-03-24

Today I stumbled across some really interesting things and I wanted to
share it via this document. If you know me, I am subscribed to quite a
number of mailing lists, one of them being gmane announce. There isn't
a particular reason why I subscribed to this other than curiosity,
messages are rare so it does not bother me.

Today a new mailing list was registered for the community around
XEphem. Now, I didn't know what was XEphem prior to reading this
mailing list, but now I am super happy to have discovered it. EXphem
is a "scientific-grade interactive astronomical ephemeris package".
The word Ephemeris comes from greek and it means diary or journal.
In astronomy, it refers to a book of tables describing the trajectory
of astronomical objects. Those books were used and are still used
today (in a more modern fashion) to navigate the sky and to study
celestial bodies.

[[https://xephem.github.io/XEphem/Site/xephem.html][XEphem]] is a powerful MIT licensed software with so many
functionalities and a look from the 90', you know this is a good
software. Even though it is practically useless to me, I started
playing with the program. Is is packaged on variaous linux
distributions and even on other operating systems such as FreeBSD and
Solaris. It looks amazing to me, I encourage you to take a look at it,
it is full of functionalities. Also the program is written in C,
beautiful C.

I then read the wikipedia page and discovered so many things. First,
cilivizations have been making ephemeris since the Babylonians in the
1st millennium BC. Moreover, the term "epoch" in astronomy refers to
a moment in time used as a reference point for some other astronomical
quantity, what is interesting is that the calendars used in astronomy
are not the same as the terrestrial ones, so sometimes there are
funny dates such as January 0.

Overall, it was fun going on a different place where I know close to
nothing about and be intrigued this much like a kid.

Some other interesting things. Someone made a [[https://www.reddit.com/r/emacs/comments/1jhjgnu/the_book_of_the_church_of_emacs_satirical_ten/][funny reddit post]] about
the 10 rules of the emacs church that was fun to read. Also, another
blogger I follow shared some photos of flowers in his city and I feel
inspired to do the same in the following days.

One last thing. Today Linux 6.14 released and the usual message from
Linus made me laugh:

#+begin_src
So it's early Monday morning (well - early for me, I'm not really a
morning person), and I'd love to have some good excuse for why I
didn't do the 6.14 release yesterday on my regular Sunday afternoon
release schedule. 

I'd like to say that some important last-minute thing came up and
delayed things. 

But no. It's just pure incompetence. 
#+end_src

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]]
