#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-05-26 - Two feelings
:PROPERTIES:
:RSS: true
:DATE: 26 May 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://san7o.github.io/giovanni-diary/ephemeris/2025-05-26.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-05-26 - Two feelings

Hi,

Today I want to talk about two feelings I experienced in the last 24
hours.  It is nothing rational, just some emotions that took me for
some time and then washed away like water in a river.  In particular,
I want to talk about the feeling of being unfit among others and how I
feel demotivated from my environment.

The first emotion is the feeling of unfitness. Yesterday I spent
many hours rewriting several pages of this diary. I was in the mood
of writing, I was focused and it felt really good, I guess a little
writer is growing inside me. I can't help but write honestly.

Since I was enjoying this so much, I thought I could share it. Hence,
I started looking for people online with a similar interest. So I
searched the web, dedicating my efforts on discord servers since this
is where many normies hang out. I found two servers, "The Writing Hub"
and "Penpals, Journaling and Stationary", and I began exploring
them. I particularly liked the idea of penpals which is the habit of
writing to somebody with letters or email. This is something I am fit
for: I consume most of my content through mailing lists and blog posts
so I am used to long form written content, and I prefer it this
way. I can express my thoughts and emotions more clearly through
writing, I can take my time to reflect and choose the right words.

In the server's presentations page, people would give a brief
description of themselves and their interests. I found many creative
people, artists, music lovers, dancers, painters, etcetera.  Here is
where my self doubts came in. My brain went something like this: "Wow,
all these people do like art, music. It must be easy for them to
socialize. My main interests are things like UNIX operating systems,
like file systems and the Linux's eBPF subsystem...". I felt like I'm
too much of a nerd to belong there, and this is one example of more
pervasive thoughts in many other areas. I do not have to fit
everywhere, yet me being me makes everything feel a little lonely and
makes it hard to find a place for me.

However I rationalized my feelings and appreciated more the fact that
we are all so different, there is value in interacting with people
from distant backgrounds. Thinking about opposite ideas than yours
will make you better understand others and your own, it makes us
question things we never thought of and refine our reasoning. I
reflected on how much I liked what I do, even if it is really
unpopular among peers. Sometimes I feel lonely in my journey, but
instead of focusing on what I don't have I should think about what
I do have.

The second feeling I felt happened just a few hour ago, I was
reflecting on how demotivating university has been. When I wanted to
go to university I had a strong drive to write good software and give
my best, I though this would be a big step up in my programming
journey since in high school I knew nobody that had similar interests
as me. Yet this was not the case, as often I was the most experienced
person in groups. I would see people wibecoding, doing exercises with
chat gpt, not even bothering giving the tiniest effort on the software
they were writing. I don't judge them, I think of others as I would
think for myself and seeing this is not pushing me to improve and give
my best. I have to say that not everything is like this, and I am
overreacting. I can't help but see what my feelings are telling me and
introspect. Yet, it is true that I don't feel pushed to give my best
in, say, contributing to open source or participating in community
projects. For my internship I was completely on my own, little to no
help from my university. I made the best out of it but it would have
been fine to just do a small project and call it a day.

From this experience I understand that what I do and where I go is
completely up to me, it is my responsibility and I should create my
own opportunities. What I talked about today may seem childish and
irrational, so are humans. I am happy that I got to think about this
tiny things, most of the time I am too focused on what I have to do
that I can't find time for myself. Maybe writing this here makes me
recognize that I am vulnerable and emotional too.

-- Giovanni

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]] 
