#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-07-12 - Unbalanced
:PROPERTIES:
:RSS: true
:DATE: 12 Jul 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-07-12.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-07-12 - Unbalanced

I officially broke by streak of journaling everyday, It went well for
a few days but I was not diligent enough. The reason being that I
worked a lot and the last few days life has been unbalanced. I want to
talk more about these two topics, starting with work.

This was my first week at the company. Even if everything was new to
me, I managed to get used to the system really quickly. By the second
day I was already developing a proof of concept which would help
another research project from one of my team members. If you have ever
done Research and Development, or research work in general, you know
that this is something that takes your mind completely which makes It
difficult to balance work and life. I felt this quite hard: I really
like the programs I am developing and I want to spend the most amount
of time possible thinking about these problems. For context, I am
working on applications that use eBPF programs in kubernetes clusters
for security services like monitoring, fingerprinting, and proxing (I
think I can't give further details). It has some operating systems
programming which is the part I like, and It has some kubernetes /
cloud involved which may be what keeps paying for a roof and food. And
so, I am really invested in my work and I usually overwork more than I
should, and when I come home I still think about the code and what I
could do better. This is partially the reason why I did not write this
diary daily, the other reason being that I come home late and I am
simply mentally tired.

If I allowed myself to take proper breaks, maybe my life would be more
balanced and I would be able to consistently write this blog. On the
other hand, there is a strong part of me that really wants to work as
much as possible and spend every bit of my energy to do work, for my
future. In fact, this part of me believes that you can achieve things
and be proud of yourself only by working really hard and by mastering
your crafts. That is what I have been doing for many years to stay
true to this. With this mentality, you may understand that It is
difficult to allow me some time for myself and to rest. However, I
realize the importance of this for my well being, the problem is that
It does not feel good in my mind. In spite of this, this evening I
think I'll take some time off and reflect more on the past week and
months, get things clear and organized.

I did not fully explore Linz yet. Today I went running next to the
river, and previously I only briefly visited the main city street. The
rest of my time outside is spent in the road between the apartment and
the office. In my defense, I tried to look for some events in the city
but I don't really care about famous singers or artistic exhibitions,
so I don't have much to do.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]] 
