#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-07-03 - Willkommen in Linz
:PROPERTIES:
:RSS: true
:DATE: 03 Jul 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-07-03.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-07-03 - Willkommen in Linz

Today is my first day in Linz Austria, I will be staying here for two
months to work for a tech company. This opportunity was somewhat
unexpected since I was not actively looking to go abroad, but then the
opportunity came and I decided to go with it.

This experience has great personal value for me. First of all, I will
be working in the industry I want to build a career in; I can finally
step out of the University bubble and see what a real day to day job
looks like. Further, I get paid for this so I can be financially
independent which is important.

Moreover, I want to see how I handle myself in a completely new
environment. I have been living alone already for three years but I
got used to my life in Trento, I enjoyed quite a stable situation and
it has been a while since I had great changes in my life.

I also don't know German, which means I have to translate everything
when I go out since the city does not put much effort helping you. As
soon as I moved in to my building, I had to fill a document with
details about myself for the immigration center; the document was in
German so it took me a while to understand everything that I needed to
write, thankfully it was not too difficult and I asked another person
to review my understanding of the words. Still, why would a document
that immigrants need to sing be in German? English is the universally
known language and chances are that people from other countries know
English. Maybe there is some policy regarding official documents, but
I think this is not helping the person that wants to enter the
country.

Once I had the document signed, I needed to bring it to a local
library where I would be registered in the country. The local library
then pointed me to go to the center in the Magistrate, which pointed
me to go to room 1109 where they handled the registration. I have to
say that everything was really fast and the people I talked to knew
where to send me.

What was.. unusual.. was how many young people I met during this
process, and while moving. The people I talked to in the Magistrate
were really young, I'd say between 21 and 25 except one which was
older. Even the girl at the city library, and the people in the
tram. This makes me sad seeing that in Italy all the young people are
fleeing the country and who's left are mostly elderly people.

Later, I bought my lunch at Eurospar and took a nap. I needed to buy
more things but then it started raining really heavily so I went to a
closer store and bought just the dinner. Even if the trip was a few
hundred meters, my pants and shoes got completely wet, thankfully
there is a dryer I can use in the building. Tomorrow I'll go to a
second hand shop and buy some plates and things to cook at a cheap
price (hopefully) so I can start cooking by myself.

I need some sleep now, the previous night I could not sleep at all in
the bus. Yet flixbusses are really nice, I payed a fraction of what I
would have payed if I were to go by train or plane.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]] 
