#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-03-19
:PROPERTIES:
:RSS: true
:DATE: 19 Mar 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-03-19.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-03-19

I was reading the post "On the Stoic harmony with nature" of Prod
where he talks of phylosophy, I wanted to save It here for the record
because It was such an interesting read:

In Greece we have a saying that comes to us from antiquity: “nothing
bad not intermixed with good” (ουδέν κακόν αμιγές καλού). A liberal
translation is “there is no pure evil in this world as everything we
find that is bad always has some good mixed into it.” The opposite is
also true, namely, that all good things have some bad inherent to them.

[...]

In nature things happen when they are meant to. Consider how trees
blossom when their spring arrives, bears hibernate during winter, rain
drops when there are clouds, and so on. No phenomenon can be decoupled
from its fundamentals and, by extension, no event can be independent
of the totality of phenomena. The same is true for the human condition,
though we may lack that kind of patience in our deeds to see how some
eventuality is the result of dynamics that build up over time.

[...]

The Greek word for “nature” is “physis” (φύσις) which refers to things
that grow. They develop organically, as noted above, and have a life
of their own that is couched in terms of the cosmic continuum of life:
they are all coexistent and interdependent. To live in accordance with
nature, then, is to go with the flow of the prevailing conditions,
else to be adaptable. When trees cannot grow directly upward because
some obstacle is in their way, they grow sideways, circumventing the
problem.

Compare this to the attitude of forcing things to happen, of declaring
our wants, and trying to implement them regardless of the prevailing
conditions. If the tree insists on only going straight up, then it
will perish. Same principle for humans. What would my life be like
had I insisted on becoming a footballer and did not show the requisite
adaptability to try new things and to ultimately find value in them?
I would probably be miserable the whole time, as I would be fighting
against forces I could not overcome, never to realise my goal, and
never to have the necessary openness to take in what the world was
showing me.

End note: thank you Prod for your wisdom.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]]
