#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-06-05 - Last University lesson
:PROPERTIES:
:RSS: true
:DATE: 05 Jun 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-06-05.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-06-05 - Last University lecture

Yesterday I had my last class lecture of my bachelor degree in
computer science. This concludes a period of three years where I
dedicated all my time to studying and mastering my crafts.  From my
part, I rarely skipped a lesson. In fact, I count less than 10 lessons
I did not attend for various reasons often not in my control, I have
always showed up even when I did not feel like going and that kept me
motivated to push through all my exams. Now I will take some time to
reflect on what has been, all while studying for my last three exams.

What I am most grateful for is being able to dedicate to my studies
fully, which is really a privilege and It won't happen again, I am on
my own now. In three years I rarely "unfocused" and when that happens
I would feel lost, thankfully I could dedicate my entire wake time and
my energies to programming and studying programming and open source
projects which is so important for me.

Did everything go smoothly? Was everything the best It could have
been? Absolutely no, yet I stopped thinking about what could have
been and instead I learned to appreciate what I have now. Probably
about 80% to 90% of my time getting this piece of paper of a degree
was not worth It, I had so many terrible exams where I learned
nothing, yet I did so much more outside university like a graphics
engine, an operating system, I hacked with the Linux kernel for
hundreds of hours and I have developed some expertise through these
projects.

If you don't know, Italian universities are very theoretical. I didn't
do many projects, anyone could get this degree with very little
knowledge of programming. Exams are hard, sometime unreasonably hard
depending on the professor, and the future is really uncertain for
students unless you emigrate to other nations. Such is the situation,
or at least how I am perceiving this right now. You see me complaining
now, however I rarely rant on things; I prefer getting things done
without much talk.

Even if I have so much to learn, I now know a little bit more than
before. It never feels enough, but It is progress and I trust the
process.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]] 
