#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-06-21 - The world changes, and so do you
:PROPERTIES:
:RSS: true
:DATE: 21 Jun 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-06-21.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-06-21 - The world changes, and so do you

I was taking a walk in a park near my room, I often go there when I
want to breathe some fresh air after a long study session or when I
feel anxious. The reason why I go to this specific park is, other than
being easy to reach, the presence of a public book crossing
shelf. There are many of those, scattered across the city, and people
can go there and leave or take any book. If nobody is greedy and
everyone leaves and takes the exact amount, then there would be a
constant number of books always changing. In reality, some people are
more generous than others and overall there is always a good amount of
books, at least 20 in this one. As always, I am curious to see whether
there are new books and if any of them interest me, so I go to the
location. As a side note, I like this place so much that I marked it
and other places in openstreetmap so that their location is registered
for others to use.

When I reached the little hose, what I found was a patch of dirt
surrounded by grass. Maybe I was mistaken about the place, so I went
back and forth on the street, but I was not mistaken. Indeed the shelf
was not there anymore, apparently it was decided that It had to be
removed from the park and it's now gone.

This reminded me that everything, even good things change. Nothing is
really forever. Obviously this is something I already knew and
experienced, and I accepted it. Likewise, we humans change both as
spices and as individuals in our short lifetime. Previously I was
reading some entries of my diary from three years ago, I noticed that
the things that moved me and the things I did as a consequence of
these were completely different. Yet some things are still the same,
it's always me but the perspective is different and how I perceived
the world is different.

When you look back at history you see how so many things change
drastically. We went from horses as a means of transportation to space
rockets in less than a century thanks to human ingenuity. When you
look really back, think about the Roman Empire or civilizations now
lost to time, the changes are so great that it is difficult even to
imagine how the world was at that time. Yet some things are the same,
the mountains that surround my city have been there for
millennial. Once, these mountains were seen as obstacles that you
needed to circumvent to reach other cities. During the first world war
they were seen as a military fortress to protect the border, now they
are seen as nature to protect.

I now feel stoic about things changing, I see this as a rule of life
so I don't feel bad when things do change. That works either way for
things that disappear and things that appear. What I can do is to hold
tight what I wish to keep with me longer to delay the inevitable.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]] 
