#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:ephemeris.org][Ephemeris]] >

* 2025-03-16
:PROPERTIES:
:RSS: true
:DATE: 16 Mar 2025 00:00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-03-16.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-03-16

I was taking a walk in my neighbourhood, there is not much too see
here. A couple of small parks, some triees, and mostly residential
houses. Yesterday I was watching a live of Prod. in real time, he was
just answering some questions from chat. He is such an interesting
and unique person, let me elaborate. Some people know him for his
philosophy videos, I belive he has a formal education in philosophy
and he often records his walks where he openly shared hit thoughts.
He lives a simple life in the mountain, with little to no human
contact or even electricity. Some other people know him for his
emacs videos: he is a maintainer of some well-known pacakges and he is
surely very knowledgable about his emacs-craft. He brings this two
worlds togheter, this is why I think he is so unique.
I started to watch his emacs videos and became interested into the
philosophy ones. What strikes me is his self aweareness. Just by
talking, he uncovered some of my own inner hazards and helped me
get more aware of them.

[ Here I have redacted some pages where I reflect about myself, I
am still unsure on how much to share here so I will redact this for
now ]

Another point of reflection of this walk was history and searching
through old stuff. In the park where I usually go there is a small
wooden shelf under some stone structure. It is one of those shelfes
where people may take or leave any book. I always stop there to see
new books and If something interests me I would take It home for
some time. Some of the books are narrative, some of them are
didactical books, most of them are very old. What fascinates me is how
those pieces of paper can open a window into the past and look at
the world from a totally different prospective. For example, there
was a local newspaper from a lot of time ago, It was one of the
first with colored ink. It looked like from another era, totally
another style. I imagined how people reading this newspaper looked
like and I find It peaceful. I am attracted to a simpler life,
and I enjoy those thoughts.

[ Here I redacted some more pages, but basically I was getting
inspired to start writing some stories ]

Anyway, I am heading back home right now. I updated my todo list with
some stuff.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]]
