#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-07-06 - Writing math proofs
:PROPERTIES:
:RSS: true
:DATE: 06 Jul 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-07-06.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-07-06 - Writing math proofs

Nothing much to tell today. I spent most of my time studying
Algorithms, right now I need to read and summarize the chapters that I
am missing. This is the most energy demanding part but hopefully I
will be done in a week or two. Once I have all my notes, I just need
to get comfortable explaining the details and the proofs, which
usually takess a lot of time but it is less intense.

Today I proved the "Master Theorem" for finding the time complexity of
certain types of recursive functions, it took me at least half an hour
to understand the proof but I finally got it and It is nice. I spent
the rest of the day playing the [[https://adam.math.hhu.de/][natural number game]] where you need to
write proof for the properties the basic operations in the natural
numbers (successor, addition, multiplication...). It is very
challenging for me since I am quite new to formal proofs and I need to
build an intuition for how these proof assistant work, but at least I
made some progress.

Eventually I want to be able to prove some theorems for cryptography
like RSA and some other fundamental theorems from calculus. I know
that Terence Tao has published a calculus book with Lean4 proofs but I
didn't read it yet.

Anyway, tomorrow I will start working at the company, which I will
refer to as D from now on. Hopefully it will go as smoothly as the
last few days have (mostly) been.

Expenses so far (same as yesterday):

#+begin_src
 Expenses                           ||           
------------------------------------++-----------
 expenses:food                      ||    $31.82 
 expenses:food:non-essential        ||     $9.20 
 expenses:household:bathroom        ||     $7.86 
 expenses:household:kitchen         ||     $8.74 
 expenses:household:washing-machine ||     $7.49 
 expenses:legal                     ||    $19.92 
 expenses:non-essential             ||     $4.45 
 expenses:rent                      ||  $1406.00 
 expenses:travel:arrival            ||    $39.47 
 expenses:travel:public-transport   ||    $60.50 
------------------------------------++-----------
                                    ||  $1595.45
#+end_src

I'll watch another episode of Better Call Saul this night.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]] 
