#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-05-14 - The role of theater in my life
:PROPERTIES:
:RSS: true
:DATE: 14 May 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-05-14.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-05-14 - The role of theater in my life

Today I went to theater as a spectator after exactly one year since
the last time I step in a stage (and I was an actor!), which made me
reflect on the role of theater in my life and the fact that its time
has come to an end for me. I feel like I have no interest to enter a
theater on my own and I surely don't have the time and mental space to
participate anymore. This moment concludes a journey of 4 years where
theater was a part of my life and now it's not, I will now explain my
journey and my thoughts.

I started theater in my last year of high school and I consider this
one of my bravest decision I ever did. I was a very introverted and
shy person (still am) and I was constantly blocked by my own self
doubt and a lack of social skills. At least I was doing great at CTF
competitions :). In the summer between my fourth and fifth (last) year
of high school I was at a point where I needed to get out there and
push myself hard, so I did and one of the things was joining a theater
class organized by my school. Surely the fact that everything was
setup by my school reduced friction. In fact, I consider myself lucky
because many schools do not have a theater group and mine had just
been created one or two years prior. If it weren't in the school I
probably would have never joined. So I was in theater, actually there
was a short creative writing class before that with the same people so
I got introduced to the group. My god that felt awkward at first, but
I slowly became more comfortable with the exercises and with the
group. By the end, going to the lessons was surely my favorite
activity (after installing Linux everywhere obviously) and it gave me
a lot of motivation and self confidence. I have to say that the
teachers were truly amazing, so was the group and the exercises. My
best memories of high school are all from theater.

But life moves on and I moved to another city far from home to pursue
my bachelor degree in computer science. My first year was a year of
great change and discovery, and I decided to keep doing theater. I
joined a local group I found via some fliers hoping to relive some
stress from university. But I was really stressed and pressured daily
so I could not fully enjoy it. Moreover, the experience was completely
different and instead of doing classic theater "creative" exercises,
we were tasked to create our own show by the end of the course. This
was a different thing than the previous year and, while it was not
bad, it was not great neither. I am perfectly conscious that the main
reason for why I didn't enjoy it It's my own fault: I was unable to let
go of myself and university was giving me a constant level of anxiety
and pressure that sat on me at any moment. The people were great too
but as I said I was the principal cause of friction.

It's now my second year of university and I decided to try theater
again, this time with another group. And none other that ATU which I
knew was the best of the best, and it was. I got selected in the group
and the lessons started, each Monday evening, in a huge theater all
for ourselves. This was a step higher than anything that I had ever
tried before, both in terms of "professionalism" and intensity.  And
surely it was intense, too much intense for me. The group was a really
active and strong one, I felt like I was the only introverted in the
room and that made me distance from the rest. Let's say that I felt
this distance increasing more and more as time passed, in particular I
discovered how much of a calm and silent person I am and how much I
really felt uncomfortable around such loud and excited people. So far
I have always kept pushing myself to get out of my own "cage" and
socialize with others, but this group completely smashed the limits
until it had the opposite effect of what It should have had giving me
a lot of anxiety. Furthermore, as the final play was getting closer,
the intensity of the lessons kept increasing. So were my university
classes and the date of the exams. By the end of the class, I was
totally overworked, sleep-deprived, stressed and anxious to the point
where this led me to a huge burnout. I was not meant to do theater, I
thought.

And so I didn't try again another year and I decided to focus on my
studies, leaving behind everything else. It's now been I year since I
stepped into a theater and I have to say that the distance between
theater and me kept increasing every day. The distance between that
life of constant stimulus and excitement, and my life of stability and
peacefulness are not compatible anymore. I never wanted that life, it
does not feel natural to me.

Doing all those years of theater has been a great experience of
discovering myself, the good and the bad.  As I transition from an
university student to a worker, I have so much things to think about
that I can't take some more. I don't feel like I have the motivation
since I am now driven by different ideals. Either way, doing theater
helped me change the course of my life and I will keep this memory in
my heart, with some bitterness and sadness that it came to an end.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]] 
