#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] > [[file:ephemeris.org][Ephemeris]] > [[file:entries.org][Entries]] >

* 2025-05-28 - Lucky and Unlucky
:PROPERTIES:
:RSS: true
:DATE: 28 May 2025 00:00 GMT
:CATEGORY: Ephemeris
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/ephemeris/2025-05-28.html
:END:
#+INDEX: Giovanni's Diary!Ephemeris!2025-05-28 - Lucky and Unlucky

Hi,

today was both the unluckiest and luckiest day that I have memory
of. Let me explain why.

This afternoon I had to present a demo of what I have been working on
for my internship. Both a researcher from a company and my professor
were present, It was the opportunity to show my work to my supervisors
so It was a big moment.

In the morning I went to university to follow lessons, then went back
home and started preparing some slides. I setup the the local
kubernetes cluster and the operator, everything was compiled,
everything was working. Suddenly my laptop turns off, with no
sign of life, 30 minutes before the presentation.

Yes, this happened. All my development setup, the cluster, how could
I demo the program without a computer? You don't.

After 0.3 nanoseconds I booted up my desktop PC and began downloading
all the dependencies, cloning all my repositories, logging in on all
my accounts and finishing my slides. I had at least 4 terminals all
running different things in parallel, and I was switching between them
faster than I have ever done. I downloaded Kind and go, setup the
local cluster, deployed the operator and tested it. And somehow...
everything worked! The internet connection, the fedora package
manager, all the dependencies were working well without additional
troubleshooting, the local cluster was online and ready, and my
application was working as expected (obviously). I finished installing
the last dependency the moment I joined the zoom call, that was
incredibly close.

-----

Travel: [[file:ephemeris.org][Ephemeris]], [[file:../theindex.org][Index]] 
