#+startup: content indent

[[file:../index.org][Giovanni's Diary]] >

* Ephemeris
#+INDEX: Giovanni's Diary!Ephemeris

Ephemeris (ἐφημερίς) is an ancient greek word meaning diary, journal.
In astronomy, ephemeris refers to a book of tables describing the
trajectory of astronomical objects.

I keep a daily diary since 2022 which I update quite regularly.
I used to write everything on paper, I then switched to Obsidian
for one year, then back to paper again and finally on Emacs org
mode. I still think that nothing beats a physical diary.

Here I will keep a sort of public diary with various thoughts and
stuff I find interesting for the record. To stay up to date with
new entries, you can subscribe to the *RSS* [[file:../feeds/feedEphemeris.rss][feed]].

*** Entries

- [[file:2025-05-15.org][2025-05-15 - The role of theater in my life]]
- [[file:2025-04-19.org][2025-04-19]]
- [[file:2025-04-07.org][2025-04-07]]
- [[file:2025-04-03.org][2025-04-03]]
- [[file:2025-03-24.org][2025-03-24]]
- [[file:2025-03-23.org][2025-03-23]]
- [[file:2025-03-19.org][2025-03-19]]
- [[file:2025-03-16.org][2025-03-16]]

-----

Travel: [[file:../index.org][Giovanni's Diary]], [[file:../theindex.org][Index]]
