#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:../autobiography/chronological.org][Chronological]] >

* Ephemeris
#+INDEX: Giovanni's Diary!Ephemeris

Ephemeris (ἐφημερίς) is an ancient greek word meaning diary, journal.
In astronomy, ephemeris refers to a book of tables describing the
trajectory of astronomical objects.

I keep a daily diary since 2022 which I update quite regularly.  I
used to write everything on paper, I then switched to Obsidian for one
year, then back to paper again and finally on Emacs org mode. I still
think that nothing beats a physical diary.

Here I will keep a sort of [[file:../my-public-diary.org][public diary]] with various thoughts and
stuff I find interesting for the record. To stay up to date with
new entries, you can subscribe to the *RSS* [[file:../feeds/feedEphemeris.rss][feed]].

Get a list of the entries [[file:entries.org][here]].

-----

Travel: [[file:../index.org][Giovanni's Diary]], [[file:../theindex.org][Index]]
