#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] > [[file:stoicism.org][Stoicism]] > [[file:notes.org][Notes]] >

* Meditations of Marcus Aurelius
#+INDEX: Giovanni's Diary!Reading!Stoicism!Meditations of Marcus Aurelius

Meditations is a series of personal writings by Marcus Aurelius, Roman
Emperor from 161-180 AD, recording his private notes to himself and
ideas on Stoic philosophy (wikipedia).

The work is divided into multiple books. Below is a summary I did of
the key ideas in each book:

1. Marcus goes on thanking his friends, family and god for his
   fortune. He is thankful for his father for letting him live a life
   without decorations and richness, he thanks his teachers,
   philosophers, his wife, his mother. He is thankful to god for being
   born without malformation and with a splendid family. He is
   thankful for all that happened to him and all that he stayed away
   from. He concludes that he thinks of himself as flesh, bones and
   reason which is the ruling part. Life is just a wind that blows,
   and not a steady one.
   
2. The second book is a collection of things to remember. The ones
   that I noted are what follows. "Why should any of there things
   that happen externally, so much distract thee?". Death is not
   shameful: if there are gods, they will be kind with you, if there
   are no gods then there is no point in life. When we die, we only
   part form this moment, even if we lived for three thousand or as
   many as ten thousands of years; we are not what we were in the past,
   so "how should a man part with that which he hath not?".

   #+BEGIN_QUOTE
   The time of a man's life is a point; the substance of it ever
   flowing, the sense obscure; and the whole composition of the body
   tending to corruption [..] Our life is a warfare, and a mere
   pilgrimage. Fame after life is no better than oblivion. What is it
   then that will adhere and follow? Only one thing, philosophy.
   #+END_QUOTE

3. Do not spend time thinking about things concerning other men: what
   he said, what he thinks, what he is about; this distracts you from
   observing yourself; If a man were to ask what you are thinking,
   answer freely and boldly. Do nothing against the will of others, be
   neither a great talker nor a great undertaker. Never lament and
   exclaim, never sigh, never want either solitude or company, live
   without either desire or fear. Do nothing rashly, remember that no
   man lives more than the present. Examine and consider all things in
   life; what is the use of it?. "To be violently drawn and moved by
   the lusts and desires of the soul, is proper to wild beasts an
   monsters". Never speak anything contrary to truth.

4. Marcus Aurelius said:
   
   #+BEGIN_QUOTE
   Consider both how quickly all things that are, are forgotten, and
   what an immense chaos of eternity was before, and will follow after
   all things: and the vanity of praise, and the inconsistency and
   variableness of human judgments and opinions [...] For the whole
   earth is but one point; and of it, this inhabited part of it, is
   but a very little part; and of this part, how many in number, and
   what manner of man are they, that will commend thee?
   #+END_QUOTE
   
   Objects do not reach the soul and are in continuous change, like an
   opinion (therefore, not virtuous). Reason is common to all men,
   then we are all part of a commonweal sharing understanding, reason
   and law like a city. Remember that after a little while, you and
   the others will die, as well as your names and memories; who is
   greedy of credit and reputation after his death should remember
   that he and everyone holding his memory will die, even if that was
   not the case, what served this credit to him anyway? . If you take
   away opinion, no man will think of himself as wrong, then there is
   no such thing as wrong. Remember the following rules: do nothing but
   follow what reason is suggesting for the good and benefit of man,
   be ready to change your mind upon correct rectifications.
   
   #+BEGIN_QUOTE
   Thou must be like a promontory of the sea, against which though the
   waves beat continually, yet it both itself stands, and about it are
   those swelling waves stilled and quieted.
   #+END_QUOTE

   The life of a main is indifferent compared to the stretch of time.
   There is an infinite chaos looking backwards and an infinite chaos
   looking forward, what difference can there be between a life of
   three days and one of three ages?


-----

Travel: [[file:stoicism.org][Stoicism]], [[file:../../theindex.org][Index]] 
