#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] > [[file:stoicism.org][Stoicism]] >

* Meditations of Marcus Aurelius
#+INDEX: Giovanni's Diary!Reading!Stoicism!Meditations of Marcus Aurelius

Meditations is a series of personal writings by Marcus Aurelius, Roman
Emperor from 161-180 AD, recording his private notes to himself and
ideas on Stoic philosophy (wikipedia).

The work is divided into multiple books. Below is a summary I did of
the key ideas in each book:

1. Marcus goes on thanking his friends, families and god for his
   fortune. He is thankful for his father for letting him live a life
   without decorations and richness, he thanks his teachers,
   philosophers, his wife, his mother. He is thankful to god for being
   born without malformation and with a splendid family. He is
   thankful for all that happened to him and all that he stayed away
   from. He concludes that he thinks of himself as flesh and bones,
   and reason which is the ruling part. Life is just a wind that
   blows, and not a steady one.
   
2. The second book is a collection of things to remember. The ones
   that I noted are what follows. "Why should any of there things
   that happen externally, so much distract thee?". Death is not
   shameful: if there are gods, they will be kind with you, if there
   are no gods then there is no point in life. When we die, we only
   part form this moment, even if we lived for three thousand or as
   many as ten thousands of years; we are not what we were in the past,
   so "how should a man part with that which he hath not?".

   #+BEGIN_QUOTE
   The time of a man's life is a point; the substance of it ever
   flowing, the sense obscure; and the whole composition of the body
   tending to corruption [..] Our life is a warfare, and a mere
   pilgrimage. Fame after life is no better than oblivion. What is it
   then that will adhere and follow? Only one thing, philosophy.
   #+END_QUOTE

3. Do not spend time thinking about things concerning other men: what
   he said, waht he things, what he is about; this distracts you from
   observing yourself; If a man were to ask what you are thinking,
   answer freely and boldly. Do nothing against the will of others, be
   neither a great talker nor a great undertalker. Never lament and
   exclaim, never sigh, never want either solitude or company, live
   without either desire or fear. Do nothing rashly, remember that no
   man lives more than the present. Examine and consider all things in
   life; what is the use of it?. "To be violently drawn and moved by
   the lusts and desires of the soul, is proper to wild beasts an
   monsters". Never speak anything contrary to truth.
   
-----

Travel: [[file:stoicism.org][Stoicism]], [[file:../../theindex.org][Index]] 
