#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] >

* Stoicism
#+INDEX: Giovanni's Diary!Reading!Stoicism

Early stoicism's ethics is based on the idea that a wise man has the
duty to **live in accordance with the armony of nature, through
reason, by being virtuous**. A vrituous man is someone that does not
follow pelasure or recreational activities, "To be violently drawn and
moved by the lusts and desires of the soul, is proper to wild beasts
an monsters" - Marcus Aurelious. A virtuous man is someone that
listens to everybody, that doesn't talk too much but not too little,
thankful to others, rigid when he needs to be...

Some of the greatest stoic philosophers include **Zeno** (the first to
introduce stoicism), **Seneca** and the Roman emperor **Marcus
Aurelius** (there are many more which I did not mention for sake of
brevity).

I like stoicism for dealing with my anxieties and worries, but I do
not consider myself a good sotic, not even a decent one. To exercise
virtue I need to consistently do the good because, as Aristotele would
say, someone is said to be virtuous if his normal state of being is
being virtuous.

Here are a few notes from my readings:

- [[file:stoicism-ethics.org][Stoicism's Ethics Notes]]
- [[file:meditations-of-marcus-aurelius.org][Meditations of Marcus Aurelius]]
  
-----

Travel: [[file:../reading.org][Reading]], [[file:../../theindex.org][Index]]

