#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../reading.org][Reading]] > [[file:stoicism.org][Stoicism]] > [[file:notes.org][Notes]] >

* Stoicism's Ethics Notes
#+INDEX: Giovanni's Diary!Reading!Stoicism!Stoicism's Ethics Notes

*** Index

1. Core Ideas
2. Virtue
3. Ethics
4. Good and Virtue
5. Value
6. Emotions
7. Justice and Cosmopolitanism
   
**Sources**: everything discussed in this page is based on the book
"La ricerca del pensiero. Storia, testi e problemi della filosofia"
volume 1B by Nicola Abbagnano and Giovanni Fornero.

*** Core Ideas

The school of Stoicism was founded by Zeno of Citium (approximately
336 - 264 a.C.), It was named after the place where they held public
lectures, which was supposed to be an open space where everyone could
participate in discussions. He thought that **life needed to be lived
following philosophy (science) to reach wisdom by exercising virtue**:
"Philosophy is exercise of virtue, through virtue itself; because
there cannot be virtue without exercising, neither exercising virtue
without virtue" - Seneca.

*** Virtue

Virtue was divided into the natural, the moral and
reason. Consequently, philosophy was divided into **physics**,
**ethics** and **logic**. In early teachings, logic was the foundation
of everything else therefore It was taught first. In physics, they
thought that there was an universal order in nature, which is
destiny. God was nature itself, forever present in everything and
perfect. I will now focus on the ethics since It is the most relevant
part nowadays.

*** Ethics

Ethics is based around the idea that every human tends to live in
harmony with the world and nature, which is perfect. This tendency was
referred to as "oikeiôsis" which could be translated to "orientation"
or "affinity". This process is moved by two forces: **instinct**,
which guides the animal to seek food and breed for his own survival,
and **reason**, which connects an human with himself and with nature in
general. Acting towards this rational order is our duty:

"The term Duty is applied to that for which, when done, a reasonable
defense can be adduced. [...] And it is an action in itself adapted to
nature's arrangements. [...] Befitting acts are all those which reason
prevails with us to do: and this is the case with honoring one's
parents, brothers and country, and intercourse with
friends. Unbefitting, or contrary to duty, are all acts that reason
deprecates, e.g. to neglect one's parents, to be indifferent to one's
brothers, not to agree with friends, to disregard the interests of
one's country, and so forth. Acts which fall under neither of the
foregoing classes are those which reason neither urges us to do nor
forbids, such as picking up a twig, holding a style or a scraper, and
the like." - Lives of eminent philosophers by Diogenes Laertius,
Hicks, Robert Drew, 1850-1929, VII, 107-109.

*** Good and Virtue

There is a distinction between good and virtue. Good is when the
rational choice is repeated with constancy until It becomes a natural
disposition, that is a virtue. Virtue can have different names based
on what It is referring to: **wisdom** for men's duties,
**temperance** for impulses, **fortress** for obstacle, and
**justice** for distributions of goods.

There is no middle ground between virtue and vice: like a piece of
wood is either straight or curve, a man is just or unjust, and not
partially one or the other. A man that is not wise is a madman, wild.

*** Value

If something does not constitute virtue, nor Its contrary, than they
are indifferent. Here stoicism tells us that if reason leads us
nowhere, for example a tragedy or wealth or beauty, we should be
indifferent. Still, sometimes there are things that should be
preferred to others that may contribute us to leave a life with
reason, which are referred to as "value".

*** Emotions

Stoic ethic rejects the value of emotions, they are just opinions not
driven by reason. They define four types of emotions: **lust** for
wealth, **delight** of wealth, **fear** of future evils, **affliction**
for present evils. In opposition to those, the wise should have power
of will, joy and caution. His condition is one of **apathy**, meaning
to be indifferent of any emotion. Note that stoicism does not say to
repress emotions, but not to engage with them at all.

*** Justice and Cosmopolitanism

Since the natural order (and reason) is something common to everyone,
all humans have a **natural right** which is the base of modern
**justice**.  For the stoic, every human is a citizen of the world,
where everyone is free. The only possible enslavement is the one of
the mad with regards to his emotions when he does not act according to
reason.

-----

Travel: [[file:stoicism.org][Stoicism]], [[file:../../theindex.org][Index]]

