#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../../subjects.org][Subjects]] > [[file:../programming.org][Programming]] >

* Linux
#+INDEX: Giovanni's Diary!Programming!Linux

In high school I participated in a cybersecurity course and played
CTFs, this was a big step up in my learning journey. I began using
Kali [[file:interjection.org][Linux]] for the competitions, I then continued to use Linux
daily. I installed Arch Linux manually for the first time on
summer 2021.

I wanted to be like the cool nerds at [[https://www.reddit.com/r/unixporn/top/?t=all][r/unixporn]] so I went the route
of insane ricing and configuration of obscure command line tools just
to look cool.  I was using [[https://github.com/San7o/nixos-dotfiles][NixOS]], of course, with all the trendy
software like kitty and other stupid crap.

I got frustrated with NixOS since it felt like a jail, so I removed
everything and I [[file:../setup.org][setup]] the most minimal system I could work on. During
this period I was getting passionate about kernel development, I
wrote a few kernel modules and I started writing my own operating
system. I was using my self compiled [[file:linux-from-scratch.org][linux from scratch]], for many
months I did not have a graphics sessions or a browser on my only
computer.

I started following the linux kernel development mailing lists and
many others. Pushing in this direction led me to an internship about
writing eBPF programs for a [[file:../kubernetes/kubernetes.org][kubernetes]] cluster which got me into cloud
computing.

-- [[file:notes.org][notes]] -
  
-----

Travel: [[../programming.org][Programming]], [[file:../../theindex.org][Index]]
