#+startup: content indent

* Optimize power consumption on Linux
:PROPERTIES:
:RSS: true
:DATE: 15 Apr 2025 00:00:00 GMT
:CATEGORY: Programming
:AUTHOR: Giovanni Santini
:LINK: https://giovanni-diary.netlify.app/programming/linux/optimize-power-consumption-linux.html
:END:
#+INDEX: Giovanni's Diary!Programming!Linux!Optimize power consumption on Linux

This documents contains notes regarding my attempts to increase
battery life on my linux laptop. I don't use my laptop for
computational-expensive tasks, I'd rather prefer my battery to last
longer. Here is a list of things I did to get closer to this goal.

This guide is focused on laptops but you can get value even for dektop
servers.

*** ACPI Specification

Before thinkering with your system, you should have a decent
understanding of how the system works, both in hardware and software,
in the context of power management. I will now give you a quick
overview of power consumption on a linux system running on the x86
architecture.

Let's start from the CPU, obviously you have read the [[https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html][intel manuals]],
in particular volume 3B chapter 16, It explains how the CPU manages
power. Similarly to other hardware components, intel CPUs implement
the [[https://uefi.org/htmlspecs/ACPI_Spec_6_4_html/][ACPI]] specfication which enables an ACPI compatible operating
system to interface with hardware devices on performance.

For processors, ACPI defines different power states within the global
working state G0, and they are called "Cx states": C0 means that the
processor is executing instructions, C1 to Cn are sleeping states
where the processor consumes less; C3 consumes less than C2 which
consumes less than C1 (but this is not specified from C4 to Cn).

Furthermore, ACPI defines "Px states" which are other states inside
C0, where P0 is maximum performance. Operating systems can change the
performance state of a core "on the fly" which is known as CPU
throttling, giving us more opportunity for optimizations.

Hardware may send interrupts that can wake up a processor from a
sleeping state, therefore you should try to minimize the number of
events (by disabling devices) or balance them efficiently across cores
(using something like [[https://linux.die.net/man/1/irqbalance][irqbalance]], for example).

Going back to ACPI, devices are also a great source of power
consumption. Hardware other than processors have "device power states"
D0 to D3 where D0 means that the device is fully on, D3 that It is
off. ACPI further defines those states for many device types (network,
storage...).

*** Linux's ACPI

An overview of the Linux's ACPI implementation can be foind [[https://www.kernel.org/doc/ols/2005/ols2005v1-pages-59-76.pdf][here]].
Briefly, It is composed of an OS Service Layer which abstracts
the hardware, an user interface via sysfs and procfs, the core
implementation which includes an AML interpreter which is used
is used as a language between the firmware and the operating
system, and other components.

On Linux, userspace can interact with the ACPI subsystem via sysfs in
=/sys/devices/LNXSYSTM:00= or =/sys/bus/acpi/devices= (if ACPI support
is enabled). Inside, you will find directories that represent ACPI
devices, for each device the directory contains informations about
them such as the status or the voltage. You may want to use something
like =acpid= or =upower= to dump ACPI info, if you are using some
linux distribution you may have something similar already installed.

Obviously, the more stuff you are doing with your computer, the more
energy It will consume. You should prefer light software compiled to
machine code, with optimizations enabled and stripped debug
information. We will discuss more what other optimizations you can
implement.

*** Understand what consumes the most

While you may try to thinker with configurations files and settings
following common heuristics (such as "less processes = less power
consumption"), It is more productive to evaluate the power consumption
of your operating system and make changes to the most power-draining
sources in order to have a greater impact on the overall power
consumption.

A general tool that works well is [[https://linux.die.net/man/8/powertop][powertop]] which will give you
per-process power consumption and information about CPU states,
devices and tunable settings to decrease power consumption. You
can calibrate the tool with =powertop --calibrate= (only on laptops)
and then wait for It to collect data for about one hour and generate
power estimation figures.

From the overview tab you can easily see which processes are
consuming more power so that you can look into them individually.
If you find that systemd is logging too much, try to increase the
time between logs, and so on.

*** Save yourself time: TLP

To save yourself some time configuring your system, you can use [[https://linrunner.de/tlp/introduction.html][TLP]]
(or any similar tool) which automatically configures the kernel with
power saving settings. It is supposed to work well out of the box but
you can manually configure the settings via a configuration file in
=/etc/tlp.conf=. Please refer to the documentation for further
details.

The installation is quite strait forward, check your package
manager. To apply a power manager profile, run the following
command (do this every time you change the configuration file):

#+begin_src bash
  sudo tlp start
#+end_src

To get system information and the status of the tool, run the
following:
#+begin_src bash
  tlp-stat -s
#+end_src

There are plenty of utilities like this, use them at your own risk.

*** Kernel Settings

There are many settings you can tune on linux, which will mostly
depend on your hardware and drivers. A decent list can be found in the
Archlinux's [[https://wiki.archlinux.org/title/Power_management][Power Management]] page.

To access the ACPI subsystem you need to have the following
enabled in your kernel (from the gentoo wiki):

#+begin_src
  Power management and ACPI options --->
  -*- Device power management core functionality
  [*] ACPI (Advanced Configuration and Power Interface) Support --->
    <*> AC Adapter
    <*> Battery
    -*- Button
    -*- Video
    <*> Fan
    <*> Processor
    <*> Thermal Zone
  
  [*] CPU Frequency scaling --->
        Default CPUFreq governor (ondemand)  --->
    -*- 'performance' governor
    <*> 'powersave' governor
    <*> 'userspace' governor for userspace frequency scaling
    -*- 'ondemand' cpufreq policy governor
    <*> 'conservative' cpufreq governor
    <*> ACPI Processor P-States driver
#+end_src

Additionally, enable Thermal and Powercap sysfs for your CPU:

#+begin_src
  Device Drivers --->
  -*- Thermal drivers --->
    (0)   Emergency poweroff delay in milli-seconds                                                                              
    [*]   Expose thermal sensors as hwmon device                                                                                
    -*-   Enable writable trip points                                                                                          
          Default Thermal governor (step_wise)  --->                                                                           
    [*]   Fair-share thermal governor                                                                                           
    -*-   Step_wise thermal governor                                                                                            
    -*-   Bang Bang thermal governor                                                                                            
    -*-   User_space thermal governor                                                                                           
    [ ]   Thermal emulation mode support
    [*]   Power allocator thermal governor   
    Intel Thermal drivers --->
        <M>   Intel PowerClamp idle injection driver
        <M>   X86 package temperature thermal driver
        < >   Intel SoCs DTS thermal driver
        <M>   Intel PCH Thermal Reporting Driver
        ACPI INT340X thermal drivers  --->                                                                                     
            <M> ACPI INT340X thermal drivers
#+end_src

And rapl, which gives additional information about the processor:

#+begin_src
  Device Drivers --->
  [*] Generic powercap sysfs driver --->
    <M>   Intel RAPL Support
#+end_src

Now you should have all the requirements to start playing with
the settings, =tlp.conf= is a good place to start.

You can choose a frequency scaling governor to manage throttling.
This will dynamically change the clock's frequency and voltage
cofiguration via P-states. Assuming you are using TLP, to list the
available governors you can run:

#+begin_src bash
   sudo tlp-stat -p | grep governor
#+end_src

To increase battery life, It is recommended to reduce the maximum
charge level below 100% and prevent the charging process to happen for
every short discharge from the maximum. By default, TLP does not set
this. To enable it, set the variables =START_CHARGE_THRESH_BATx= and
=START_CHARGE_THRESH_BATx= to something like =75= and =80=, where =x=
represent the number of the battery in your laptop.  Sadly, on some
laptops (lime my HP one) this is not supported and the command
=tlp-stat -b= would output
=/sys/class/power_supply/BAT1/charge_control_start_threshold (not available)=.

*** Helpful tips

Here is a list of other helpful things that will make your operating
system lighter and more efficient.

**** Light graphics session

If you are using a graphical environment, chances are that you do not
need a full blown desktop environment to manage the position of your
windows. The lighter your window manager, the better. My argument is
that all you need is a program that can create windows and move them;
such program should be simple and small, understandable and hackable.
Everything else is bloated software, I would suggest something like
[[https://dwm.suckless.org/][dwm]] or [[https://www.ctwm.org/index.html][ctwm]].

I did not compare Wayland-based window managers against X11, I found
some benchmarks [[https://www.phoronix.com/news/GNOME-Xorg-Wayland-AMD-Renoir][online]] and they are similar in power consumption but
the benchmarks were with Gnome. Unless you find a really minimal
window manager using wayland, the good old simple X11 window managers
are the best.

**** Have less background processes running

If you are using a linux distribution instead of compiling your system
on your own, chances are that the maintainers of said distribution
have enabled a buch of stuff you don't really need. This goes from
kernel modules for various hardware, which you do not need, to
background daemons to do things like reporting crashes.

If your system uses systemd, you can check active services using the
=systemctl status= command. Even though many of them may be idle and
may not contribute much to the overall power consumption, they still
consume resources so It is helpful to have less things running in
your system.

Disable things like bluetooth if you don't need it, crash reporting
daemons, etc...

-----

Travel: [[file:./linux.org][Linux]], [[../../theindex.org][Index]]
