#+startup: content indent

[[file:../../index.org][Giovanni's Diary]] > [[file:../../subjects.org][Subjects]] > [[file:../programming.org][Programming]] > [[file:notes.org][Notes]] >

* Offline Programming
#+INDEX: Giovanni's Diary!Programming!Notes!Offline Programming

I often practice offline programming, it is something I want to share
with other people throught this post. Offline programming means what
it means: to go totally offline while doing that I like, which happens
to be programming. Of course the joy of being offline is not limited
to programming, it can be reading, writing, debugging, etc.

But hey, "just disconnect from the internet" you may say, and I would
totally agree with you. Except the fact that we have become so reliant
on the internet that this is not so straightforward. I grew up
assuming I could find help in online forums like stackoverflow
whenever I needed it. New generations will grow up assuming they can
use LLMs to answer all their questions (which can be good and bad, I
will leave this discussion for another day). But when you are offline,
you are on your own.  It's just me, the computer / compiler and the
program I am writing, and I LIKE this!

How do I use a certain API? I may keep doing what I know but at a
certain point I will need to do something I don't know, how can I
learn new information?

I think being able to figure out all of this on my own is a great
skill to have. Moreover, when I program offline I have less
distractions.  Since I don't need an internet connection, I can be
wherever I want as long as my battery lasts (so I am [[file:../linux/optimize-power-consumption-linux.org][optimizing for
power consumption]] in my kernel configuration). Offline, I tend to
take more breaks and actually rest in silence instead of watching a
youtube video. I may start paying attention to the sound of the birds
or the movement of the clouds, or deeply reason about the problem I
have, since there is no other way around it.

Back to the question, how do you learn more stuff. Unsurprisingly,
people have been collecting many forms of knowledge throughout
history, even before the internet! In software, this can be
documentation or actual source code. Of course, some programs are more
documented than others, with the best example probably being emacs
which has a huge offline documentation pre-installed in each emacs
build, and each package is easily explorable. I will prefer simple,
free and open source software over any other, so that I can understand
it and modify it as I need / want. I will use something like Linux
From Scratch instead of depending on an already existing linux
distribution to do package management for me. Anyway, getting used to
reading source code is probably the best thing you can learn.

But you already knew all of this, the question becomes how do I
learn something that is not related to programming. People back
in the day created what is referred to as an encyclopedia, a collection
of basically everything. The modern version would be wikipedia,
which you can download locally. I find this very helpful, especially
for math and history.

To do offline work you will need software that works offline
(duh). Instead of google docs, you can use libre office or [[file:../emacs/emacs.org][emacs]]. You
can download music locally and use a local music player, or emacs. You
can download book and films and store them forever in your hard drive.

When I am offline I feel like I am in total control of my computer,
everything is compiled from source and my system is stable. Further, I
don't really need to worry about cybersecurity anymore.

The point of this post is that I like practicing being completely
offline for long periods of time, while still doing what I consider
productive tasks as a programmer. Of course, your work may require and
internet connection, but you can choose how to spend your own free
time afterwards and I decided to spend it offline.

Related article:
- [[file:usb-for-apocalypse.org][USB for the Apocalypse]]

-----

Travel: [[file:../programming.org][Programming]], [[file:../../theindex.org][Index]]
