Hi, I am Giovanni

I am a curious and kind person, reserved and introspective - I am quite the
introvert!

You'll always find me studying in libraries, silently reading or reflecting in
my diaries. I often understand both sides of an argument, and I am a better
listener than I am a speaker; I look for simple things in life and profound
connections

I am really deep into my interests. I enjoy journaling, reading non-fiction,
playing the piano, writing short stories and poetry, learning about the history
of my surroundings, technology and its evolution.

I like having slow conversations, sharing personal experiences and reflections,
exploring ideas. If you are interested, feel free to write to me! I am a friendly
person, although I may take time to reply.

INTJ, Enneagram 5w4

#+HTML: <details><summary><a>My PGP key</a></summary>

#+begin_src
-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEaoYRShYJKwYBBAHaRw8BAQdASF2cNrv70IaSjghyakOCQq6QwzunJCNnPfq3
jZFttma0JUdpb3Zhbm5pIDxnaW92YW5uaS5zYW50aW5pQHByb3Rvbi5tZT6IkAQT
FgoAOBYhBCGZ2daunGp2pSYIPE+l3gTCxygJBQJqhhFKAhsDBQsJCAcCBhUKCQgL
AgQWAgMBAh4BAheAAAoJEE+l3gTCxygJngEA/2fd5kgz6U5qiWVXbyVZcIHJhCyU
mxuL8FESeWo+d+rJAQCO8cbxZmKM4SYv97GYfXb18lz6tcYO/2DBMovaS3v5Bbg4
BGqGEUoSCisGAQQBl1UBBQEBB0BhmTZJzL3HAIPP6sp/wuu9ZTHgSpArExJj6mUe
jGXYEQMBCAeIeAQYFgoAIBYhBCGZ2daunGp2pSYIPE+l3gTCxygJBQJqhhFKAhsM
AAoJEE+l3gTCxygJy3AA/2bp5q0jlM1xw2lIndjVQijNOHnE4foHFmvdNZ68mADM
AP98Pxc4KnVhV3oyitEQyG0T9aEhDjqPE4HExS6lVt/6AQ==
=xl1c
-----END PGP PUBLIC KEY BLOCK-----
#+end_src

#+HTML: </details>

[[mailto:giovanni.santini@proton.me][giovanni.santini@proton.me]]

[[file:./index.org][back]]
