* Snowflake

Idea: convey the atmosphere of the room at MIT when computers were discovered,
and the first graphical application "snowflake" was shown. This was felt as a
legendary moment, like a gamer moment.

Acts:

- Intro
- Act I: entering the room
- Act II: loading the program
- Act III: admiring the snowflake

Characters:

- Ken: 16yo Hacker, he wrote the program, is very exited to show it to the
  others. The smart type of person, a bit reserver
- John: 20yo Hacker, he is driven and wants to push the technology and his
  skills to te maximum. He does not shower.
- Matt: 18yo Hacker, more hardware oriented, he is more physically driver, he
  touches things, acts, does not want to wait

** Text

Intro

Something legendary was happening in the second floor of Building 26 at MIT,
what people called the "Kludge Room" because of how cahotic and experimental it
was.

"Come oon, let us in!"

"Kids, just please.. take a walk around the corridor and let us finish"

The three students were not backing off so easily, they have been waiting all
day for this. It was late and the labs were closing, that was the only moment
where they would have a change.

"Ken, "

Act I

Act II

Act III

