#+startup: content indent

[[file:../../../index.org][Giovanni's Diary]] > [[file:../../../subjects.org][Subjects]] > [[file:../../writing.org][Writing]] > [[file:../poetry.org][Poetry]] > [[file:favourites.org][Collected Favourites]] >

* To the unknown journeyman
#+INDEX: Giovanni's Diary!Writing!Poetry!Collected Favourites!To the unknown journeyman

#+begin_src
To the unknown journeyman
I promise to show courage
in upholding my vows

What is an adventure
if not the commitment
to keep going?
#+end_src

By Protesilaos Stavrou, 2025-08-11, [[https://protesilaos.com/poems/2025-08-11-unknown-journeyman/][original link]].

** Comment

Truly beautiful and powerful words from Prot, as always. I feel
greatly moved by this poem.

From Wikipedia, a journeyman is "a worker, skilled in a given building
trade or craft, who has successfully completed an official
apprenticeship qualification.". He is someone that showed dedication
and fought through adversities to master his skill: someone can can be
looked up to. Yet there are many "unknown" journeymen, especially in
the world of programming, there are so many professionals that are
doing excellent and critical work but are greatly under-recognized and
underappreciated (maybe Prod is thinking of his condition, and the
one of other maintainers).

Someone that mastered their skills can motivate us into working harder
and harder. It surely does for me. He made a promise to himself, and
so do I, to never give up.

The second part of the poem explores this idea, and it words it
beautifully.

I find a deep stoic meaning in this poem, to keep going through
life nevertheless.

-----

Travel: [[file:favourites.org][Collected Favourites]], [[file:../../../theindex.org][Index]] 
