#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:stash.org][Stash]] >

* Piano
#+INDEX: Giovanni's Diary!Stash!Piano

I started playing piano at a young age. I was fortunate enough to have
many family members who play instruments even professionally or just
for passion, so it was easy to find a rusty keyboard that I could play
with.  I followed lessons from a friend of my father for a some time,
however I liked discovering songs by myself and being self tough so I
stopped going shortly after.

I have a beautiful Yamaha P525, the only luxurious thing I own.

My favorite composer is Ludovico Einaudi, and has always been since
the very first days. I have a deep emotional connection with many of
his songs, I dedicated hundreds if not thousands of hours playing his
songs over my lifetime, I even went to a live concert in Siracusa.  My
favorite above all is [[https://youtu.be/3uFG-T1yiHg?si=Df8Tjwwd0zqNCH4F][Nuvole Bianche]]. The only author that comes
close to him is Ryan O'Neal aka Sleeping At Last, I also have a strong
emotional connection to his songs.

Fortunately, I recorded and uploaded many of my performances [[https://www.youtube.com/@giovannisantini6094/videos][on
youtube]] so I can rewatch them now. Unfortunately most of the videos
are with the old rusty keyboard. I like playing songs from Yiruma in
particular [[https://youtu.be/3-mf49DLpOw?si=SxmHwNg6i78hT6eD][River Flows in You]], various [[https://youtu.be/J-8SGnwsDYI?si=YVZmziXnQTlegH-K][anime music]] especially from
[[https://youtu.be/HtxVl4dozxY?si=ZJNTdSTMEoHdH7TC][Radwimps]].

-----

Travel: [[file:stash.org][Stash]], [[file:../theindex.org][Index]] 
