#+startup: content indent

[[file:../index.org][Giovanni's Diary]] > [[file:stash.org][Stash]] >

* Volunteering
#+INDEX: Giovanni's Diary!Stash!Volunteering

I volunteered on various associations for several years. This was part
of my identity, I believed in the value of volunteering and in the
associations I was participating with. Coincidentally, Trento was
selected as the European Capital of Volunteering for 2024 so there was
a lot of movement in this area.

I joined [[https://www.caritas.org/][caritas]] in my home town, I was preparing dishes for the poor.
In Trento I joined [[https://www.sat.tn.it/][SAT]] where I was organizing Hikes with groups of
kids, sometimes I did trail maintenance. I then joined [[https://fondoambiente.it/][FAI]] for some
time to promote history. I guess contributing on [[file:../programming/notes/contributing-to-openstreetmap.org][openstreetmap]] is
considered volunteering.

Unfortunately I had to stop to focus on my career, but once I will
be more setup I am looking forward to do volunteering again.

-----

Travel: [[file:stash.org][Stash]], [[file:../theindex.org][Index]] 
